alphagov/pay-tech-docs

manifest.yml

renaming from rename app to `govukpay-tech-docs` --> `govukpay-docs`

PP-2481 rename app to `govukpay-docs`

---

deploy.sh

rename app to `govukpay-docs` in deploy script

PP-2481 rename app to `govukpay-docs` in deploy script

---

source/documentation/16-support-contact-and-more-information.md

Add in content to existing support section, adapted from GOV.UK Support Overview documentation.

Expand Support Section

---

source/documentation/15-contribute.md

Making it clear that we are now Open Source for our application code and link to our key components.
Make it easier for others to understand what code we have and how it hangs together.

Open source clarification

---

LICENCE

Adding a licence.
As per standards.

Adding a licence

---

source/documentation/04-quick-start-guide.md
source/documentation/06-api-reference.md
source/documentation/14-security.md

Replace Production with Live - Quick Start Guide, API Reference & Security

Replace Production with Live

---

source/documentation/03-before-you-start.md

Changes include:
- References to the service manual for team capability, the getting started guide, and creating an account
- Removing information on points of contact and PSP contracts
The PCI DSS content should be going in the Getting Started page

Miscelleaneous changes - Before You Start

---

source/documentation/08-refunding-payments.md

- Corrected title formatting
- Added extra content on payment failures to Refund Notifications section
- Added Refund Destination section; please check if this is accurate as I used the Stripe content as a base and I'm unsure if our functionality is the same

Miscellaneous changes - Refunding a Payment

---

source/documentation/04-quick-start-guide.md

- Removed introduction and 1st numbered bullet under Account setup as unnecessary
- Added introduction to Making a test API call section
- Clarified 1st numbered bullet in Making a test API call section
- Added additional sub-headings: "Follow end user payment journey" and "View transaction at GOV.UK Pay Admin site"
- Added in content around expiry date format

Miscellaneous Changes - Quick Start Guide

---

README.md

Whitespace to test webhook fix

---

config/tech-docs.yml

Change TOC level from 3 to 6 to ensure sub-headings visible

Correct mistake on TOC

---

source/documentation/14-security.md

- Added content on PCI compliance requirements, based on number of transactions.
- Added table on SAQ A questionnaire

Update to PCI DSS Section

---

source/documentation/07-integration-details.md

Correct bullet formatting in "Accepting returning users" section

Correct bullet formatting

---

source/documentation/10-switching-to-production.md

Added in ePDQ screenshots to ePDQ section. A google doc with these screenshots has already been reviewed by Rory.

Add in ePDQ screenshots

---

source/documentation/14-security.md

Updated PCI DSS content in line with Bryan Scaife's feedback

Update PCI DSS content

---

source/documentation/03-before-you-start.md

Markdown fix to ensure HTML blockquote rendered

---

source/documentation/14-security.md

Removed references to channel and specified that the PCI DSS compliance criteria are based on merchant and scheme (Visa, Mastercard).
Worth discussing with Bryan Scaife before approving.

PCI DSS Changes

---

source/documentation/02-about-govuk-pay.md
source/documentation/03-before-you-start.md
source/documentation/05-payment-overview.md

Added content for following:
- Responsive design for payment pages
- Sub-title on the typical timescales for integrating a new service into Gov.UK Pay
- Sub-title on the costs of using the service

PP-2652 question optimisations

---

source/documentation/14-security.md

Amended PCI DSS content in line with Bryan Scaife email from 12 October 2017

PCI DSS Tweaks

---

config/tech-docs.yml

We say Get started everywhere else so updated to say the same here

PP-2695 - Getting Started to Get started

---

source/documentation/04-quick-start-guide.md
source/documentation/05-payment-overview.md
source/documentation/06-api-reference.md
source/documentation/07-integration-details.md
source/documentation/08-refunding-payments.md
source/documentation/09-testing-govuk-pay.md
source/documentation/11-troubleshooting.md
source/documentation/12-architecture.md
source/documentation/13-versioning.md
source/documentation/14-security.md
source/documentation/16-support-contact-and-more-information.md
source/documentation/18-glossary-of-terms.md

Ensure that headings follow logical progression from H1 to H2 to H3 to H4

Correct heading levels

---

source/documentation/08-refunding-payments.md

Update reference in "Refunds from the admin site" section to transaction+list+image+4.png

transaction+list+image+4.png

---

source/documentation/10-switching-to-production.md

Updated worldpay settings image reference to image folder rather than on AWS

update worldpay-settings1 image

---

source/documentation/08-refunding-payments.md

Updated reference to refund-payment-button.png in images folder rather than on AWS

refund payment button image update

---

source/documentation/06-api-reference.md

Change "error code" to "status code" as it includes successful payments codes
Change O to 0 in last API error codes table

Fix a few small errors

---

source/documentation/05-payment-overview.md

Added content on resuming a payment

Added "Resume a payment" section

---

source/documentation/01-this-documentation.md

Changed title to Documentation for GOV.UK Pay in with request from @tillwirth

Updated title

---

source/documentation/14-security.md

The "Process more than 6 million transactions per year" section was duplicated and I removed the duplicate.

Remove duplicated section

---

source/documentation/06-api-reference.md

Put the base URL in a callout box and made it bold

Made base URL more obvious

---

source/documentation/03-before-you-start.md

Added content and links for:
- Make a demo payment
- Test your service with your users

Document two new features

---

source/documentation/09-testing-govuk-pay.md

PP-1503 add link to smartpay test card numbers

---

source/documentation/06-api-reference.md

- Added section on API errors caused by payment status
- Added subtitle to distinguish API error caused by API call from errors driven by payment status

API error codes update

---

source/documentation/10-switching-to-production.md

Added Smartpay content to Switching to live section

Add Smartpay content

---

source/documentation/10-switching-to-production.md

- Added in Smartpay to Generate API key section
- Added in links to live gateway setup sections
- Correct sub-bullet formatting in Smartpay > Enable roles and accounts
- Added content on how to set up 3D Secure for ePDQ

Set up 3D Secure for ePDQ

---

source/documentation/02-about-govuk-pay.md
source/documentation/04-quick-start-guide.md
source/documentation/05-payment-overview.md
source/documentation/06-api-reference.md
source/documentation/07-integration-details.md
source/documentation/10-switching-to-production.md

Updated documentation url to new service url
solo @belindac

PP-3379 Change documentation link in header and footer

---

source/documentation/04-quick-start-guide.md
source/documentation/05-payment-overview.md
source/documentation/07-integration-details.md
source/documentation/08-refunding-payments.md
source/documentation/09-testing-govuk-pay.md
source/documentation/11-troubleshooting.md
source/documentation/14-security.md

Removes all negative contractions per https://www.gov.uk/guidance/style-guide/a-to-z-of-gov-uk-style#contractions

Negative contractions

---

source/documentation/10-switching-to-production.md

This matches the words that are actually on the page

Change “Edit organisation details” to “Organisation details”

---

source/documentation/07-integration-details.md

because content is about 18 months out of date...

update docs for financial reporting integration

---

source/documentation/02-about-govuk-pay.md

Removes emphasis on government and makes it clear it's for all public sector

Change language in intro re. "government"

---

source/documentation/05-payment-overview.md

Removes ambiguity and potential for confusion with [API] endpoint

'end point' -> 'end'

---

source/documentation/16-support-contact-and-more-information.md

'Deskpro' -> 'Zendesk'

---

.github/ISSUE_TEMPLATE.md
.github/PULL_REQUEST_TEMPLATE.md

Adds templates in .github directory for issues and PRs

Adds templates for issues and pull requests on GitHub

---

deploy-to-test.sh

to enable our tech writer to be able to deploy to the test instance on PaaS

PP-4010 Add script to deploy to test

---

source/documentation/welsh_payment_pages.md
source/optional_features/index.html.md.erb

Adds optional features section and introduces Welsh language
Adds an "Optional features" section on the same hierarchy as other h1s and introduces a section on Welsh language as part of that
Viewable live at: https://govukpay-docs-optional-features.cloudapps.digital/optional_features/#optional-features

Adds optional features section and introduces Welsh language

---

source/documentation/api-reference.md
source/documentation/optional-features.md
source/documentation/refunding-payments.md
source/documentation/security.md
source/documentation/support-contact-and-more-information.md
source/documentation/testing-govuk-pay.md

Some of the tables on the docs aren't rendering correctly, brought to light by recent changes to the "Optional features" docs
A temporary fix for this. In time I'll try to find a more permanent solution but this will be at a lower level.

Temporary fix for tables

---

source/documentation/custom_branding.md

We shouldn't reference specific software
Removes reference

Remove reference to specific software

---

source/documentation/quick-start-guide.md

As part of my ongoing review of the documentation I am going through each section in turn and making suggested changes. Much of this will be simple but some of the changes in given PRs will need more thorough reviews by subject matter experts (SMEs). This is because I may introduce language which could be phrased more clearly by an SME, and of course I may make mistakes.
The quick start guide did not confirm to GDS style entirely and I made some changes to the language to make it more active and straightforward for users to follow. I also copied some information we have from elsewhere about testing with return URLs in a sandbox environment (i.e. not needing HTTPS), in case users only get this far into their journey before wondering about that.

Quick start guide changes

---

source/versioning/index.html.md.erb

Suggestion for new Versioning section, merge-conflict free (matches new directory structure)
New version of Versioning section
Replaces https://github.com/alphagov/pay-tech-docs/pull/133

Overhaul Versioning section

---

source/api_reference/index.html.md.erb
source/optional_features/custom_branding/index.html.md.erb
source/optional_features/delayed_capture/index.html.md.erb
source/optional_features/welsh_language/index.html.md.erb
source/payment_flow_overview/index.html.md.erb
source/payment_links/index.html.md.erb
source/switching_to_live/index.html.md.erb
source/testing_govuk_pay/index.html.md.erb

Some links are broken. 
Fixes some broken links, changes directory name from "taking_payments" to "making_payments" to align with the section title inside.

Fix broken links

---

source/reporting/index.html.md.erb

Missing "__", renders badly
Fixes by adding "__"

Missing "__"

---

source/optional_features/corporate_card_surcharges/index.html.md.erb

Wires got slightly crossed when this was merged but this is a non-essential (just me recommending) content edit.
Very minor content/language edit(s).

Language tidy-up

---

source/payment_flow_overview/index.html.md.erb

Some of the content in the 'Payment flow' page flow is incorrect after updates to GOV.UK Pay 
First attempt to change to reflect new state

Minor changes to payment flow page to reflect current truth

---

source/account_structure/index.html.md.erb

The account structure page is in the wrong place and has broken images
Puts the account structure page between 'testing' and 'switching to live', and fixes the images

fix account structure page

---

source/api_reference/index.html.md.erb
source/quick_start_guide/index.html.md.erb
source/refunding_payments/index.html.md.erb
source/security/index.html.md.erb
source/switching_to_live/index.html.md.erb
source/testing_govuk_pay/index.html.md.erb

Changes all instances of 'sandbox' to 'test'

Sandbox to test

---

source/optional_features/delayed_capture/index.html.md.erb

Per PP-4297, can now get a capture URL for a single payment
Adds amendments based on PP-4297 to reflect recent updates to delayed capture feature (
This is a first draft: for now it would be great to just understand if this is on the right lines @alexbishop1 @katiebates many thanks

Delayed capture amendments

---

source/switching_to_live/set_up_a_live_worldpay_account/index.html.md.erb

Fixes error in Worldpay Switching to Live documentation (steps 3-5 in… 'Set up your profile' section)

Inaccuracy in Worldpay STL content

---

source/testing_govuk_pay/index.html.md.erb

The 'Testing' section breaks style in some places
Language rework per above

Reworks the 'Testing' section

---

source/refunding_payments/index.html.md.erb

Language/style (relatively minor) revamp of the 'Refunds' section, including rework notably of the content surrounding email notifications
I've added my own review comment to this for potential reviewers: would be great to get this sorted before proceeding

Revamp of 'Refunds' section, most notably of email notifications section

---

source/payment_flow/index.html.md.erb

Correct "exammple" to "example"

Correct exammple to example

---

source/testing_govuk_pay/index.html.md.erb

Some of the Testing section does not conform to style 
Fixes style of some elements of Testing section and adds reference to the new "how to" API integration guide

Testing section small revamp, reference to Integration guide 

---

source/making_payments/index.html.md.erb
source/reporting/index.html.md.erb

Fixes 'Search payments' broken links to Gelato (API explorer)

Fixes broken Gelato links

---

source/testing_govuk_pay/index.html.md.erb

Fixes broken link to section on mock card numbers

Fixes broken link in Testing section

---

source/quick_start_guide/index.html.md.erb

you can now also search for refunds by date range

Added info about refunds

---

source/payment_flow/index.html.md.erb

Added reference to "direct redirect"

---

source/testing_govuk_pay/index.html.md.erb

Improved instructions and required approval for performance testing

---

source/integrate_with_govuk_pay/index.html.md.erb

Minor typos and added reference about HTTP in test accounts

---

source/optional_features/welsh_language/index.html.md.erb

Reference to default language

---

source/payment_flow/index.html.md.erb

Added that HTTP can be used in test accounts but not in live accounts

---

source/security/index.html.md.erb

Clarify handling of API keys

---

source/switching_to_live/set_up_a_live_worldpay_account/index.html.md.erb

Clarified  some steps in the Worldpay set up process

---

config/tech-docs.yml
source/api_reference/index.html.md.erb
source/direct_debit/index.html.md.erb

Direct Debit documentation, to be introduced in stages for review

Direct Debit documentation

---

source/direct_debit/index.html.md.erb
source/refunding_payments/index.html.md.erb

Changes post @katiebates review.
Move direct debit section to after the refunding payments section.
Change "A payment changes states as it moves through its lifecycle" to "An agreement changes states as it moves through its lifecycle".
N/A

direct debit tweaks

---

source/switching_to_live/set_up_a_live_worldpay_account/index.html.md.erb

Tweak Amex content after discussion with @alexbishop1 and tech writer 2i
Tweak Amex content after discussion with @alexbishop1 and tech writer 2i
Tweak Amex content after discussion with @alexbishop1 and tech writer 2i

Tweak Amex content

---

source/switching_to_live/before_you_switch_to_live/index.html.md.erb

There is a new switching to live process.
New content to reflect the new switching to live process.

Stl new process

---

source/optional_features/digital_wallets/index.html.md.erb
source/optional_features/index.html.md.erb

Google Pay and Apple Pay are launching.
New content for Apple Pay and Google Pay.

Create digital wallets content

---

source/optional_features/welsh_language/index.html.md.erb
source/payment_links/index.html.md.erb

Service teams can now create payment link payment pages in Welsh.
Update the 'Payment links' and 'Welsh language payment pages' pages with content about creating Welsh payment links.

Payment links in Welsh

---

source/optional_features/welsh_language/index.html.md.erb
source/payment_links/index.html.md.erb

Reverts alphagov/pay-tech-docs#288 - published this too early!

Revert "Payment links in Welsh"

---

source/optional_features/welsh_language/index.html.md.erb
source/payment_links/index.html.md.erb

Republishes the changes that were already reviewed and merged in https://github.com/alphagov/pay-tech-docs/pull/288 (then reverted in https://github.com/alphagov/pay-tech-docs/pull/289)
See previous pull request.
Just a quick check that it looks the same as before.

Payment links in Welsh (republish)

---

source/optional_features/delayed_capture/index.html.md.erb

Update the delayed capture page to explain what the feature is and why you might use it.
Two sentences added to the delayed capture page.
Please review for factual accuracy.

Clarify delayed capture

---

source/payment_flow/index.html.md.erb

Adding documentation about when a payment will arrive in a merchant's bank account.
Added a line to the 'Payment flow' page.

Add line about time to payment

---

source/direct_debit/index.html.md.erb
source/payment_flow/index.html.md.erb

Add documentation about the updates to the Direct Debit API.
- Update the Direct Debit page
- Add a line in Payment Flow to link users to the Direct Debit page for recurring payments

Update Direct Debit API documentation

---

config/tech-docs.yml

BAU replace google analytics id

---

source/switching_to_live/before_you_switch_to_live/index.html.md.erb

Got a support ticket where someone couldnt understand why they couldnt login to pay-admin 😱

BAU - Go live link was linking to pay-admin 😱

---

source/optional_features/delayed_capture/index.html.md.erb

This is a redo of closed pull request: https://github.com/alphagov/pay-tech-docs/pull/339.

PP-5676: Change capture time to 5 days

---

source/integrate_with_govuk_pay/index.html.md.erb
source/payment_flow/index.html.md.erb

We're missing some of the detail about how long it takes a team to receive a payment ("payout") in their bank account after a user completes their payment.
- Add more detail about how long it takes to receive a payment
- Move these docs to the 'Finance and accounting systems' of the 'How to integrate' page, which is where we're currently meeting the need of reconciling payments

Add documentation about payout times

---

source/index.html.md.erb

We need to add a review date to a single page so that we can test the [review monitoring](https://github.com/alphagov/pay-tech-docs/pull/384) is working.
Add a review date to the front page.

Add review date to front page

---

source/account_structure/index.html.md.erb

We've had questions from service teams about how to set up their services in Pay.
Rejig the content to help avoid confusion about team members having access to different services.

Clarify account structure and user accounts

---

source/security/index.html.md.erb
source/switching_to_live/index.html.md.erb

We need to add documentation about ways to prevent fraudulent payments.
Add a 'Preventing fraudulent payments' section to the [Security](https://docs.payments.service.gov.uk/security/#security) page.

Add documentation about fraudulent payments

---

source/optional_features/custom_metadata/index.html.md.erb

Daniel The Manual Spaniel alerted us to https://docs.payments.service.gov.uk//optional_features/custom_metadata/ needing review. It's now been checked and is free of factual errors.
Update review date
Please check if ok

Update review date for metadata page

---

source/index.html.md.erb
source/making_payments/index.html.md.erb
source/optional_features/custom_branding/index.html.md.erb
source/optional_features/moto_payments/index.html.md.erb
source/optional_features/prefill_user_details/index.html.md.erb
source/optional_features/use_your_own_error_pages/index.html.md.erb

We're doing a fact check of all documentation pages so we can add Daniel The Manual Spaniel review dates to the documentation as a whole.
Makes factual fixes and adds review dates to the first set of documentation pages we've checked.
Please check it all looks ok.

Update review dates and fix factual issues (part 1)

---

source/security/index.html.md.erb

Daniel the Manual Spaniel reported that the Security page was up for review.
Update the 'last reviewed' date.

Update security page review date

---

source/support_contact_and_more_information/index.html.md.erb

It'd be useful to call out the automated notifications of incidents, so that we can point to it when engaging with service teams.

Call out the updates and notifications

---

source/optional_features/moto_payments/index.html.md.erb

Daniel the Manual Spaniel has reminded us that the MOTO page needs reviewing.
Updated the review date to later because we plan to look at the MOTO page later this week. We'll change the review date again after we've made any content changes.

Update review date on MOTO page

---

ci/pipeline.yml
source/switching_to_live/set_up_a_live_stripe_account/index.html.md.erb

- Move the pipeline to `pay-tech-docs`
- Builds tech dosc on PRs and reports the status

PP-6606 Pipeline in Tech Docs

---

source/account_structure/index.html.md.erb
source/direct_debit/index.html.md.erb
source/optional_features/block_prepaid_cards/index.html.md.erb
source/refunding_payments/index.html.md.erb
source/reporting/index.html.md.erb

We're doing a fact check of all documentation pages so we can add Daniel The Manual Spaniel review dates to the documentation as a whole.
Makes factual fixes and adds review dates to the third set of documentation pages we've checked.

Add review dates and make factual fixes

---

source/payment_flow/index.html.md.erb

fix broken link

---

ci/pipeline.yml

It currently requires a Concourse team admin to push pipeline changes, for which there is a minimal audit trail and some scope for error.
Permit auto-deployment of CI pipeline changes when merged to master. Requires any PRs to be reviewed and merged in the usual way

BAU: Enable Self-updating Concouse pipeline

---

source/digital_wallets/index.html.md.erb
source/set_up_3dsecure/index.html.md.erb
source/switching_to_live/index.html.md.erb

Add content on Strong Customer Authentication

---

source/making_payments/index.html.md.erb

Update Review Date

---

.secrets.baseline
source/index.html.md.erb
source/security/index.html.md.erb
source/support_contact_and_more_information/index.html.md.erb

Update the doc review date and add `.secrets.baseline`

BAU Update Review Date For Docs

---

source/digital_wallets/index.html.md.erb

Add into docs that we don’t pass on cardholder details unless those details are collected in the service

[WIP] Fact-check-a-thon - Digital Wallets

---

source/integrate_with_govuk_pay/index.html.md.erb
source/refunding_payments/index.html.md.erb
source/reporting/index.html.md.erb

Jira ticket: https://payments-platform.atlassian.net/browse/PP-6973
Add in content on new settlement API.

DO NOT MERGE UNTIL FEATURE IS LIVE - Payouts api

---

source/contribute/index.html.md.erb

The fact check a thon checked the accuracy of the tech docs.
Add the following apps to the contribute page:
- pay-products
- pay-products-ui
- pay-direct-debit-connector
- pay-direct-debit-frontend
- pay-ledger

Fact check a thon - Contribute

---

source/moto_payments/index.html.md.erb

You can now hide or unhide card information for MOTO payments.
Add guidance on this.
Check that this is accurate and reflects the user journey.

Add in guidance on how to hide card information in MOTO payments

---

source/testing_govuk_pay/index.html.md.erb

https://payments-platform.atlassian.net/browse/PP-6794

Fact Check a Thon - Test your integration

---

source/api_reference/index.html.md.erb
source/versioning/index.html.md.erb

As per https://payments-platform.atlassian.net/browse/PP-6791

Fact Check a Thon - Versioning

---

source/moto_payments/index.html.md.erb

Small changes after tech writer 2i

Hide card info in MOTO payments - Post 2i small changes

---

package.json

- bump js-commons version to 3.0.2

PP-6284 bump pay-js-commons version

---

source/optional_features/custom_branding/index.html.md.erb

- Docs are a reflection of the world as it is

BAU Update Review Date

---

source/moto_payments/index.html.md.erb

Multiple support tickets have highlighted a need to clarify the MOTO docs.
Clarify the following:
- how to enable MOTO payments on a live account vs a test account
- how to set up MOTO payments for Worldpay / ePDQ vs Stripe
- what MOTO screens look like
Check it lines up with https://payments-platform.atlassian.net/browse/PP-7278.

Improve MOTO content

---

source/contribute/index.html.md.erb
source/corporate_card_surcharges/index.html.md.erb
source/delayed_capture/index.html.md.erb
source/digital_wallets/index.html.md.erb
source/integrate_with_govuk_pay/index.html.md.erb
source/moto_payments/index.html.md.erb
source/optional_features/welsh_language/index.html.md.erb
source/payment_flow/index.html.md.erb
source/quick_start_guide/index.html.md.erb
source/reporting/index.html.md.erb
source/security/index.html.md.erb
source/switching_to_live/index.html.md.erb
source/switching_to_live/set_up_a_live_epdq_account/index.html.md.erb
source/switching_to_live/set_up_a_live_smartpay_account/index.html.md.erb
source/switching_to_live/set_up_a_live_stripe_account/index.html.md.erb
source/switching_to_live/set_up_a_live_worldpay_account/index.html.md.erb
source/testing_govuk_pay/index.html.md.erb
source/versioning/index.html.md.erb

Regular review of the docs is important.
Ensure that every doc page has a review date and it lines up with https://docs.google.com/spreadsheets/d/1xouJvNmeYfq2g5VpEEMNXfv77uc5S6QvOrFX-o3qy_M/edit?ts=5f44e4f6#gid=0

Add review dates

---

source/payment_flow/index.html.md.erb

https://payments-platform.atlassian.net/browse/PP-7245

Clarify how expired payments work

---

source/moto_payments/index.html.md.erb
source/security/index.html.md.erb

Make consistent with security product page as per https://payments-platform.atlassian.net/browse/PP-6800.
Includes feedback from Mark Willcox.

Fact check a thon - Security

---

source/payment_flow/index.html.md.erb

Correct link

---

source/switching_to_live/index.html.md.erb
source/switching_to_live/set_up_a_live_epdq_account/index.html.md.erb
source/switching_to_live/set_up_a_live_smartpay_account/index.html.md.erb

Supplementary fixes to https://payments-platform.atlassian.net/browse/PP-7440

Supplementary A11y Fixes

---

source/switching_to_live/set_up_a_live_worldpay_account/index.html.md.erb

https://payments-platform.atlassian.net/browse/PP-7546
Implement fixes to improve Worldpay go live docs:
- Make it clear which screen you are in for each step
- "Refused by bank" - users unable to check the checkbox in merchant channel

Changes to Worldpay go live content driven by Gwent Police

---

source/integrate_with_govuk_pay/index.html.md.erb

- Reviewed content for factual errors and all looks good
- Sets the review date to today's date

PP-7457 Update 'Integrate with the GOV.UK Pay API' page review date

---

source/payment_flow/index.html.md.erb
source/quick_start_guide/index.html.md.erb

Changes in line with:
- https://payments-platform.atlassian.net/browse/PP-7597
- https://payments-platform.atlassian.net/browse/PP-7598

Fact-Check-A-Thon December 2020

---

source/optional_features/welsh_language/index.html.md.erb

No changes needed for this page - updating the review date only.

PP-6632: Use Welsh page is up to date

---

source/account_structure/index.html.md.erb
source/block_prepaid_cards/index.html.md.erb
source/refunding_payments/index.html.md.erb

- there were no issues with any of these pages thus only update the last_reviewed field

PP-7601 review and update fact check

---

source/reporting/index.html.md.erb
source/support_contact_and_more_information/index.html.md.erb

- No issues found - update review date for:
- Support page
- Reporting page

PP-7601 Tech docs review

---

source/api_reference/index.html.md.erb
source/making_payments/index.html.md.erb

Reviewed the following pages (no changes required):
https://docs.payments.service.gov.uk/making_payments
https://docs.payments.service.gov.uk/api_reference

PP-6632 Update review dates for 2 pages

---

source/reporting/index.html.md.erb

Fact check has spotted 2 places where we use unnecessary quote marks in field names.
Remove the quote marks.

PP-7617 Fix code style typos on 2 pages

---

source/direct_debit/index.html.md.erb

Replacing the content about signing up for the Direct Debit pilot with contacting us about taking part in research. 

PP-7721 Replace Direct Debit content with research contact

---

source/set_up_3dsecure/index.html.md.erb

A fact check on the 3DS page have highlighted some things that need fixing. 
Factual amends.
@alexbishop1 - adding you as just wanted to check if we have the steps right under '### Set up 3DS2 (3DS Flex)'?

PP-7719 Update 3DS page with fact check amends

---

source/delayed_capture/index.html.md.erb
source/optional_features/prefill_user_details/index.html.md.erb
source/set_up_3dsecure/index.html.md.erb

Make factual fixes to issues that were found in the January 2021 fact check.

PP-7644 Fact check fixes for January 2021

---

source/custom_metadata/index.html.md.erb

- page is right, updated review date.

PP-7727 review and fact check custom metadata

---

source/switching_to_live/set_up_a_live_epdq_account/index.html.md.erb
source/switching_to_live/set_up_a_live_smartpay_account/index.html.md.erb
source/switching_to_live/set_up_a_live_stripe_account/index.html.md.erb
source/switching_to_live/set_up_a_live_worldpay_account/index.html.md.erb

- the pages contained in this commit are all correct, links are working and fact checked

PP-7727 review and fact check go live pages

---

source/switching_to_live/index.html.md.erb

A fact check highlighted an issue with the content on the go live page.
Update the journey to PSP settings. (I've handed off to the UI after reaching **Settings** because it's intuitive from there. Describing the steps in too much detail is more work for the user - and increases the risk the content will fall out of sync with UI changes.)

PP-7727 Fix to go live page after fact check Feb 2021

---

config/tech-docs.yml

- add "features" link to top navigation bar

PP-7725 add "Features" to top navigation bar

---

Gemfile
Gemfile.lock

Reverts alphagov/pay-tech-docs#564

Revert "Bump govuk_tech_docs from 2.1.1 to 2.2.0"

---

config/tech-docs.yml

PP-7844 Remove Beta tag

---

source/delayed_capture/index.html.md.erb
source/making_payments/index.html.md.erb
source/payment_flow/index.html.md.erb

- Updated API browser references with relevant API section links of the docs

PP-7883 Remove remaining API browser references

---

Gemfile
Gemfile.lock

PP-7895 Update tech-docs-gem to 2.2.2

---

source/custom_metadata/index.html.md.erb

Factual review custom_metadata page.

PP-7653 review custom_metadata page

---

source/custom_metadata/index.html.md.erb

Pay is releasing the ability to search for payments by their custom metadata. This is a UI-only change - no API changes. We don't tend to exhaustively document UI processes in the tech docs but there is precedence for mentioning functionality.
This change adds a sentence to the 'Add custom metadata' docs page to let users know this search is possible.

PP7941 / PP7940 - Lets users know that it is possible to find a payment by searching for its metadata

---

source/making_payments/index.html.md.erb

- These fields should have commas separating them from other fields

BAU Fix JSON Structure

---

source/contribute/index.html.md.erb
source/making_payments/index.html.md.erb
source/support_contact_and_more_information/index.html.md.erb
source/testing_govuk_pay/index.html.md.erb

These pages were checked and didn't need any changes, updated the last
reviewed dates.
Fixed some missing punctuation in source/contribute/index.html.md.erb

PP-8046 Update last reviewed dates

---

source/digital_wallets/index.html.md.erb
source/index.html.md.erb
source/optional_features/custom_branding/index.html.md.erb
source/quick_start_guide/index.html.md.erb
source/security/index.html.md.erb

- review and fact check tech docs March 2021 edition
- no need for any changes
- updated the last reviewed dates.

PP-8045 Tech docs - review and fact check (March 2021)

---

source/direct_debit/index.html.md.erb

The current 'Take a Direct Debit payment' page refers to research taking place in February and March 2021. Now that discovery for DD payments is complete, the page should be updated.
This PR updates the page to explain what Direct Debit payments are planned and provides a link to the GOV.UK Pay Roadmap, which will, when updated next week, provide additional information on the development of recurring and Direct Debit payments.

PP-8085 - Updates Direct Debit page to reflect new Pay Roadmap

---

source/direct_debit/index.html.md.erb
source/versioning/index.html.md.erb

Stephen Daly reviewed and suggested changes for these pages.
Changes to the pages have been made but I forgot to update the 'Last reviewed' date - this PR fixes that.

Updates review dates to reflect April docs reviews

---

source/api_reference/index.html.md.erb
source/optional_features/welsh_language/index.html.md.erb
source/quick_start_guide/index.html.md.erb

Minor changes to the formatting of some headers and corrected labelling of UI elements from the GOV.UK Pay admin

Minor changes to wording and formatting

---

source/moto_payments/index.html.md.erb

Reviewed the content and it looks good.
However, next time we update this, we could release telephone payment links as a public beta / live feature.

Updated the review date

---

source/direct_debit/index.html.md.erb

I've reviewed the content and it looks good.

Update the review date

---

source/moto_payments/index.html.md.erb
source/testing_govuk_pay/index.html.md.erb

These pages were reviewed in 2021 but the date was not updated correctly.
Two 2020 dates changed to 2021.

Corrected two review dates

---

source/accessibility.html.md.erb

The latest Tech Docs Template update has made parts of the template inaccessible. The accessibility statement for the Pay documentation needs to be updated to reflect this.
Adds suggested wording from Jon Glassman (TW that updated TDT accessibility statement) to reflect the non-compliance of the TDT until it is updated.
Tech docs template will be updated by the end of July to fix accessibility issues.

Updated accessibility statement to reflect non-compliance in TDT

---

source/block_prepaid_cards/index.html.md.erb
source/optional_features/welsh_language/index.html.md.erb
source/refunding_payments/index.html.md.erb

Updated review dates for pages that have been reviewed

Updated review dates for Refunds, Using Welsh, and Block Prepaid Cards

---

source/api_reference/index.html.md.erb

Updates review date for API reference.

Updated API reference review date

---

source/support_contact_and_more_information/index.html.md.erb

Updated Support review date

---

source/accessibility.html.md.erb

The Tech docs template has been updated to fix 3 of 4 existing accessibility issues.
Update accessibility statement to update review dates, fix links to TDT accessibility statement.

Updated a11y statement to reflect updated TDT

---

source/account_structure/index.html.md.erb
source/account_structure/set_up_where_payments_go/index.html.md.erb
source/account_structure/set_up_where_services_link_to/index.html.md.erb
source/corporate_card_surcharges/index.html.md.erb
source/integrate_with_govuk_pay/index.html.md.erb
source/making_payments/index.html.md.erb
source/optional_features/use_your_own_error_pages/index.html.md.erb

- check facts and links of tech doc files that are up for review.

PP-8361 fact check tech docs 08/21

---

source/delayed_capture/index.html.md.erb
source/direct_debit/index.html.md.erb
source/optional_features/custom_branding/index.html.md.erb
source/optional_features/prefill_user_details/index.html.md.erb
source/set_up_3dsecure/index.html.md.erb
source/switching_to_live/index.html.md.erb
source/switching_to_live/set_up_a_live_epdq_account/index.html.md.erb
source/switching_to_live/set_up_a_live_stripe_account/index.html.md.erb
source/switching_to_live/set_up_a_live_worldpay_account/index.html.md.erb

- These pages are overdue for a review. No factual error, broken link or any needed stylistic improvement has been found.

PP-8546 review and fact check 08/21 part 2

---

source/switch_payment_service_provider/switch_psp_to_stripe/index.html.md.erb
source/switching_to_live/set_up_a_live_stripe_account/index.html.md.erb

Updated KYC regulations mean that new features must be added to Pay. This PR updates the tech docs to reflect these changes.
This PR updates:
- Go Live guidance for Stripe
- Switch PSP to Stripe guidance
This has already been reviewed by Krishna, Justin, and a tech writer.

PP-8903 - KYC updates to documentation

---

source/switch_payment_service_provider/switch_psp_to_stripe/index.html.md.erb
source/switching_to_live/set_up_a_live_stripe_account/index.html.md.erb

Follow on from this [PR](https://github.com/alphagov/pay-tech-docs/pull/673).
Additional minor changes from further reviews.

PP-8903: Additional changes following review and demo.

---

source/contribute/index.html.md.erb
source/custom_metadata/index.html.md.erb
source/digital_wallets/index.html.md.erb
source/index.html.md.erb
source/quick_start_guide/index.html.md.erb
source/security/index.html.md.erb
source/support_contact_and_more_information/index.html.md.erb
source/testing_govuk_pay/index.html.md.erb
source/versioning/index.html.md.erb

- planned review of pages that are due to be reviewed
- small correction on the contribute page

PP-8837 review and fact check 10/21

---

source/block_prepaid_cards/index.html.md.erb
source/making_payments/index.html.md.erb
source/optional_features/custom_branding/index.html.md.erb
source/optional_features/welsh_language/index.html.md.erb
source/switch_payment_service_provider/index.html.md.erb
source/switch_payment_service_provider/switch_psp_to_stripe/index.html.md.erb
source/switch_payment_service_provider/switch_psp_to_worldpay/index.html.md.erb

PP-9115 Tech docs - review and fact check (January 2021)

---

ci/pipeline.yml

bau: Make the job name more accurate

---

source/account_structure/index.html.md.erb
source/account_structure/set_up_where_payments_go/index.html.md.erb
source/account_structure/set_up_where_services_link_to/index.html.md.erb
source/corporate_card_surcharges/index.html.md.erb
source/integrate_with_govuk_pay/index.html.md.erb
source/moto_payments/index.html.md.erb
source/optional_features/use_your_own_error_pages/index.html.md.erb
source/payment_flow/index.html.md.erb
source/refunding_payments/index.html.md.erb
source/reporting/index.html.md.erb

PP-9299 Tech docs - review and fact check (February 2021)

---

source/switch_payment_service_provider/switch_psp_to_stripe/index.html.md.erb
source/switching_to_live/set_up_a_live_stripe_account/index.html.md.erb

- the url of the responsible person page has been changed on product pages. Update links accordingly.

PP-9285 update responsible person page url

---

source/reporting/index.html.md.erb

Clarifies behaviour around the `fee` response attribute.

Minor tweaks based on Zendesk feedback.

---

source/accessibility.html.md.erb
source/delayed_capture/index.html.md.erb
source/direct_debit/index.html.md.erb
source/making_payments/index.html.md.erb
source/optional_features/prefill_user_details/index.html.md.erb
source/set_up_3dsecure/index.html.md.erb
source/support_contact_and_more_information/index.html.md.erb
source/switching_to_live/set_up_a_live_stripe_account/index.html.md.erb
source/switching_to_live/set_up_a_live_worldpay_account/index.html.md.erb

PP-9399 review and fact check 05/22

---

source/api_reference/create_a_payment_reference/index.html.md.erb
source/api_reference/refund_payment_reference/index.html.md.erb

- Fixed request examples for `create a payment` and `refund payment` API.

BAU - Fix curl examples

---

source/contribute/index.html.md.erb
source/custom_metadata/index.html.md.erb
source/digital_wallets/index.html.md.erb
source/index.html.md.erb
source/optional_features/custom_branding/index.html.md.erb
source/quick_start_guide/index.html.md.erb
source/security/index.html.md.erb
source/testing_govuk_pay/index.html.md.erb
source/versioning/index.html.md.erb

PP-9738 review and fact check 06/22

---

source/account_structure/set_up_where_payments_go/index.html.md.erb
source/block_prepaid_cards/index.html.md.erb
source/making_payments/index.html.md.erb
source/optional_features/welsh_language/index.html.md.erb
source/support_contact_and_more_information/index.html.md.erb
source/switch_payment_service_provider/index.html.md.erb
source/switch_payment_service_provider/switch_psp_to_stripe/index.html.md.erb
source/switch_payment_service_provider/switch_psp_to_worldpay/index.html.md.erb
source/switching_to_live/index.html.md.erb

PP-9894 review and fact check 08/22

---

source/account_structure/index.html.md.erb
source/account_structure/set_up_where_services_link_to/index.html.md.erb
source/corporate_card_surcharges/index.html.md.erb
source/integrate_with_govuk_pay/index.html.md.erb
source/moto_payments/index.html.md.erb
source/optional_features/use_your_own_error_pages/index.html.md.erb
source/payment_flow/index.html.md.erb
source/refunding_payments/index.html.md.erb
source/reporting/index.html.md.erb

PP-9991 review and fact check 08/22

---

source/switch_payment_service_provider/switch_psp_to_worldpay/index.html.md.erb
source/switching_to_live/set_up_a_live_worldpay_account/index.html.md.erb

- we no longer have an option to toggle 3ds on/off in selfservice. Remove any and all references.

PP-9752 remove 3ds toggle option

---

source/moto_payments/index.html.md.erb
source/moto_payments/moto_admin_tool/index.html.md.erb
source/moto_payments/moto_api/index.html.md.erb
source/moto_payments/moto_send_card_details_api/index.html.md.erb

Updates review dates

---

source/api_reference/create_a_payment_reference/index.html.md.erb
source/making_payments/index.html.md.erb

Additional, minor changes to finish [PP-9989](https://payments-platform.atlassian.net/browse/PP-9989).

PP-9989 clean up

---

source/delayed_capture/index.html.md.erb
source/optional_features/custom_branding/index.html.md.erb
source/optional_features/prefill_user_details/index.html.md.erb
source/recurring_payments/index.html.md.erb
source/switching_to_live/set_up_a_live_stripe_account/index.html.md.erb
source/switching_to_live/set_up_a_live_worldpay_account/index.html.md.erb
source/webhooks/index.html.md.erb

- Fact-checked and updated the review date for the following pages.
- Delay taking a payment
- Prefill payment fields
- Connect your live account to Worldpay
- Connect your live account to Stripe
- Receive automatic payment event updates using webhooks
- Take recurring payments
- Add custom branding
- Any changes to these docs will be done separately.

PP-10287 Update review date

---

source/accessibility.html.md.erb
source/api_reference/cancel_payment_reference/index.html.md.erb
source/api_reference/capture_payment_reference/index.html.md.erb
source/api_reference/create_a_payment_reference/index.html.md.erb
source/api_reference/payment_event_reference/index.html.md.erb
source/api_reference/refund_payment_reference/index.html.md.erb
source/api_reference/search_refunds_reference/index.html.md.erb

PP-10446 review and fact check 11.22 part 2

---

source/api_reference/payment_refunds_reference/index.html.md.erb
source/api_reference/refund_status_reference/index.html.md.erb
source/making_payments/index.html.md.erb
source/support_contact_and_more_information/index.html.md.erb

These pages have been reviewed with no changes required:
- Get information about a payment's refunds API reference
- Take a payment
- Support
- Send card details to authorise a MOTO payment API reference

PP-10447 Review Tech Docs

---

source/accessibility.html.md.erb

- update the last reviewed date of the accessibility page

PP-10446 update last reviewed date

---

source/api_reference/send_card_details_moto_reference/index.html.md.erb
source/contribute/index.html.md.erb
source/custom_metadata/index.html.md.erb
source/digital_wallets/index.html.md.erb
source/index.html.md.erb
source/quick_start_guide/index.html.md.erb
source/security/index.html.md.erb
source/testing_govuk_pay/index.html.md.erb
source/versioning/index.html.md.erb

- Fact-checked and updated the review date for the pages due for review.
- Also fixed a few broken links

PP-10463 Review and fact check pages due

---

source/quick_start_guide/index.html.md.erb

- Fix typo to restore link on Quick Start page

PP-10463 Tech Docs Review

---

source/api_reference/single_payment_reference/index.html.md.erb

- helpdesk request notifying support that an example JSON response was badly formatted
-  amend example JSON response to conform to JSON RFC 8259
- formatting changes only, amends have been tested by a JSON validation tool

ZD5179223 fix JSON formatting errors

---

source/making_payments/index.html.md.erb
source/support_contact_and_more_information/index.html.md.erb

PP-10799 review and fact check (March 2023)

---

source/account_structure/index.html.md.erb
source/account_structure/set_up_where_payments_go/index.html.md.erb
source/account_structure/set_up_where_services_link_to/index.html.md.erb
source/moto_payments/index.html.md.erb
source/moto_payments/moto_admin_tool/index.html.md.erb
source/moto_payments/moto_api/index.html.md.erb
source/moto_payments/moto_send_card_details_api/index.html.md.erb

PP-10891 review and fact check 04 23

---

source/api_reference/index.html.md.erb
source/recurring_payments/index.html.md.erb

Since the recurring payments beta, we've changed our approach to idempotency slightly.
This PR:
- adds guidance for generating an `Idempotency-Key`
- changes existing HTTP status codes to account for idempotency errors
- adds information about HTTP status codes to the recurring payments docs
- removes placeholder information about idempotency

PP10817: Updates idempotency information

---

package.json

BAU update pay-js-commons to 3.8.13

---

source/reporting/index.html.md.erb

PP-10988 review and fact check 05/23

---

ci/pipeline.yml

To be in line with our other repos disable concourse execution on PRs from forks.

BAU: Standardise PR settings

---

source/api_reference/refund_payment_reference/index.html.md.erb
source/api_reference/refund_status_reference/index.html.md.erb
source/api_reference/search_refunds_reference/index.html.md.erb
source/refunding_payments/index.html.md.erb

- Reviewed and updated the last review date for refund docs
- Updated search refunds example to match CURL request and also fixed next_url

PP-11116 Fact check refund docs

---

source/contribute/index.html.md.erb

Add the webhooks service to the contribution list and put the repositories in alphabetical order

BAU: Add webhooks to contribute page

---

source/accessibility.html.md.erb
source/api_reference/payment_refunds_reference/index.html.md.erb
source/api_reference/send_card_details_moto_reference/index.html.md.erb
source/delayed_capture/index.html.md.erb
source/index.html.md.erb
source/quick_start_guide/index.html.md.erb

PP-11269 review and fact check 07/23 part 1

---

source/digital_wallets/index.html.md.erb
source/integrate_with_govuk_pay/index.html.md.erb
source/making_payments/index.html.md.erb
source/payment_flow/index.html.md.erb
source/support_contact_and_more_information/index.html.md.erb

PP-11270 review and fact check 07/23 part 2

---

source/block_prepaid_cards/index.html.md.erb
source/corporate_card_surcharges/index.html.md.erb
source/optional_features/prefill_user_details/index.html.md.erb
source/optional_features/use_your_own_error_pages/index.html.md.erb
source/optional_features/welsh_language/index.html.md.erb
source/prefill_payment_links/index.html.md.erb

PP-11284 review and fact check 07/23 part 3

---

source/testing_govuk_pay/index.html.md.erb

Tiny change to change `2022` to `2023` in a `last_reviewed_on` date.

Fix a review date

---

source/api_reference/search_disputes_reference/index.html.md.erb
source/disputes/index.html.md.erb

PP-11334 review and fact check 08/23

---

source/switch_payment_service_provider/index.html.md.erb
source/switch_payment_service_provider/switch_psp_to_stripe/index.html.md.erb
source/switching_to_live/index.html.md.erb
source/switching_to_live/set_up_a_live_stripe_account/index.html.md.erb

PP-11353 review and fact check 08/23 part 2

---

source/api_reference/cancel_agreement_reference/index.html.md.erb
source/api_reference/create_an_agreement_reference/index.html.md.erb
source/api_reference/search_agreements_reference/index.html.md.erb
source/api_reference/single_agreement_reference/index.html.md.erb
source/recurring_payments/index.html.md.erb
source/switching_to_live/set_up_a_live_worldpay_account/index.html.md.erb
source/webhooks/index.html.md.erb

PP-11435 review and fact check 09/23

---

config/tech-docs.yml

BAU redirect the manual spaniel

---

source/api_reference/create_a_payment_reference/index.html.md.erb
source/api_reference/search_payments_reference/index.html.md.erb
source/api_reference/single_payment_reference/index.html.md.erb
source/making_payments/index.html.md.erb
source/moto_payments/index.html.md.erb
source/moto_payments/moto_admin_tool/index.html.md.erb
source/moto_payments/moto_api/index.html.md.erb
source/moto_payments/moto_send_card_details_api/index.html.md.erb

PP-11630 review and fact check 10/23

---

source/support_contact_and_more_information/scheduled_maintenance/index.html.md.erb

This PR:
* lets users know what their paying users and technical teams should expect if they try to use GOV.UK Pay during the maintenance windows
* clarifies when we'll update our status pages with information about the contingency windows

PP-11837: additional information about postgres updates

---

source/support_contact_and_more_information/scheduled_maintenance/index.html.md.erb

Fixes broken links and re-adds content from previous PP-11837 PR.

PP-11837: Fix 

---

.github/workflows/run-tests.yml
.github/workflows/static.yml

We want to serve tech-docs from Github Pages rather than PAAS. 
Actions workflow to build and deploy static pages.

PP-11813-deploy-tech-docs-to-github-pages

---

source/refunding_payments/index.html.md.erb

https://payments-platform.atlassian.net/browse/PP-12004

PP-12004: Updates the refund statuses to account for ePDQ and Smartpay

---

config/tech-docs.yml

Changing Daniel's barking location so that I can experiment with barking across multiple channels.

Updates the Slack channel that Daniel barks in for Nathan's experiments

---

source/api_reference/send_card_details_moto_reference/index.html.md.erb
source/disputes/index.html.md.erb
source/moto_payments/moto_send_card_details_api/index.html.md.erb
source/recurring_payments/index.html.md.erb

This PR:
* adds introductions to some API request and response examples where they were previously missing
* corrects a 'you do not need to' to 'you must not'

PP-12465: Small changes based on feedback and inconsistencies

---

source/accessibility.html.md.erb
source/api_reference/index.html.md.erb
source/contribute/index.html.md.erb
source/digital_wallets/index.html.md.erb
source/integrate_with_govuk_pay/index.html.md.erb
source/optional_features/custom_branding/index.html.md.erb
source/reporting/index.html.md.erb
source/security/index.html.md.erb
source/support_contact_and_more_information/index.html.md.erb
source/testing_govuk_pay/index.html.md.erb

PP-12078 review and fact check 01/24

---

source/quick_start_guide/index.html.md.erb

Update the last_reviewed_on field for quick_start_guide

PP-12078 update last reviewed on

---

source/reporting/index.html.md.erb

Removes a line related to now-unsupported Bring Your Own Contract functionality.

Removes an old BYOC detail

---

source/digital_wallets/index.html.md.erb
source/moto_payments/moto_admin_tool/index.html.md.erb
source/moto_payments/moto_api/index.html.md.erb
source/quick_start_guide/index.html.md.erb

This is the first docs PR for the simplified Settings pages in GOV.UK Pay.
This PR affects:
* Quick start
* Digital wallet payments
* Admin-initiated MOTO
* API-initiated MOTO

PP-13395: First wave of new Settings docs

---

source/refunding_payments/index.html.md.erb
source/switch_payment_service_provider/switch_psp_to_stripe/index.html.md.erb
source/switch_payment_service_provider/switch_psp_to_worldpay/index.html.md.erb

This PR updates the following pages to reflect the simplified Settings work:
* Switch PSP to Stripe
* Switch PSP to Worldpay
* Refund a payment

PP-13395: Update Switch PSP pages to reflect new Settings

---

source/integrate_with_govuk_pay/index.html.md.erb
source/testing_govuk_pay/index.html.md.erb
source/webhooks/index.html.md.erb

This PR changes the following pages to reflect the new simplified Settings:
* test your integration with GOV.UK Pay
* integrate with GOV.UK Pay
* webhooks

PP-13395: Update webhooks, testing, and integration pages with simplified Settings changes
