source/documentation/02-about-govuk-pay.md
source/documentation/04-quick-start-guide.md
source/documentation/05-payment-overview.md
source/documentation/06-api-reference.md
source/documentation/07-integration-details.md
source/documentation/18-glossary-of-terms.md

Updated internal tech doc links so that they point to the correct place in the new location of the tech docs, rather than pre-existing gelato documentation. Also added in an extra sentence into the Glossary section so that the table renders correctly.

Update Internal Tech Doc links

---

source/documentation/02-about-govuk-pay.md

Update the About GOV.UK Pay Section:
- Remove statement that platform will be connected to single PSR during beta
- Add clarification that platform only supports taking payments, or providing refunds
- Detail the agencies that we are working with to mirror the product page

Update About GOV.UK Pay section

---

source/documentation/09-testing-govuk-pay.md
source/documentation/10-switching-to-production.md

Add ePDQ setup content
- Added link to ePDQ mock card numbers to Testing GOV.UK Pay section
- Added setup of ePDQ content section to Switching to Production
- Replaced "production" with "live"
- Tweaked heading levels in Switching to Production
NB: Will add screenshots once screenshot queries for new tool are resolved.

Add ePDQ content

---

source/documentation/04-quick-start-guide.md
source/documentation/05-payment-overview.md
source/documentation/06-api-reference.md
source/documentation/07-integration-details.md
source/documentation/08-refunding-payments.md

Update API explorer links to open in new tab in following markdown files:
- Quick Start Guide
- Payment Overview
- API Reference
- Integration details
- Refunding payments

Update API explorer links to open in new tab

---

deploy.sh

There was a completely redundant call to credstash that could leak
credentials to the output, remove.

PP-2592 avoid leaking PaaS creds to output during deploy

---

source/documentation/10-switching-to-production.md

Updated content in line with Till / Rory email from 12 October 2017: 
- Moved "Set up GOV.UK Pay account credentials" content to "Switching to Live" section so that it applies to both WorldPay and ePDQ rather than just ePDQ.
- Added link to quick start guide section on generating an API key.
- Added links to ePDQ setup section.

Update Switching to Live section

---

source/documentation/04-quick-start-guide.md
source/documentation/05-payment-overview.md
source/documentation/06-api-reference.md
source/documentation/07-integration-details.md
source/documentation/08-refunding-payments.md

Correct API explorer URLs to v1.0.1 in multiple sections of documentation

Correct API explorer URLs to v1.0.1

---

source/documentation/10-switching-to-production.md

Added "Complete merchant details" section to "Switching to live" section, specifying that the merchant has to be the one with an account with the PSP, and that merchant details apply across test and live accounts.

Add "Complete merchant details" section

---

source/documentation/10-switching-to-production.md

Updates to the Switching to Live section:
- Changes to the GOV.UK Pay account setup to remove ePDQ-only information
- Specify that SHA-IN and SHA-OUT passphrases are plain text strings
Related to story: https://payments-platform.atlassian.net/browse/PP-2831

Switching to live updates

---

source/documentation/10-switching-to-production.md

Made some quick corrections to the "Set up live account credentials" section:
- ePDQ fields list should now render as a list
- Worldpay introductory sentence added
- Changed ePDQ and Worldpay titles from h3 to h4 to ensure correct information architecture

Corrections to "Set up live account credentials"

---

source/documentation/09-testing-govuk-pay.md

Change the “Worldpay test card numbers” link from:
http://support.worldpay.com/support/kb/gg/corporate-gateway-guide/content/reference/usefultables.htm#Test
… to:
http://support.worldpay.com/support/kb/gg/corporate-gateway-guide/content/reference/testvalues.htm#Test
… which seems to be where the test card numbers are now.
with @DanailMinchev

Update Worldpay test card numbers URL

---

source/documentation/04-quick-start-guide.md

The button to add an API key does not appear unless you are logged in to Gelato, which has confused some users and caused support requests.
- Add an instruction to log in
- Change “Add API Credentials” to “Add API Key” because that’s what the button is labelled now
- Don’t refer to button as being blue because it seems to be green if you don’t have any API keys yet
- Remove reference to non-existent screenshot

Instruct users to log in to Gelato before adding an API key

---

source/documentation/06-api-reference.md

https://github.com/alphagov/pay-connector/pull/608 has extended the expiry window to 90 minutes, so our tech docs should reflect that.

PP-3512 Extend expiry window time to 90 minutes

---

source/documentation/05-payment-overview.md
source/documentation/07-integration-details.md

Added "Payment flow: Payment expires" section. 
Changed "GOV.UK Pay will eventually expire incomplete payments" to "GOV.UK Pay will expire incomplete payments after 90 minutes" in the "When a user doesn’t complete their payment journey" section.

Make 90 minutes payment expiry time more explicit

---

source/documentation/02-about-govuk-pay.md

from 5 to 10 
+ took out reference to BEIS since we're not currently partners

update depts/agencies Pay is partnered with

---

source/documentation/10-switching-to-production.md

- Merchant details has been moved out of settings to "My services" – update navigation instructions
- We don't show which type of live account it is. It just says "Live card" –  remove reference to psp
- Broken link in email: added "mailto"
- In the research visit, when clicking the lefthand nav for Worldpay, it navigates that header to the top of the page. Text says "Complete the fields on this page:" and users were confused about which page. Added  "Account credentials page" to make it more clear if they have missed the navigation instructions at the start.

Small updates based on DCMS research trip

---

source/documentation/06-api-reference.md

We shouldn't use exclamation marks in government documentation. This rogue one should be a full stop.

Remove exclamation mark

---

source/documentation/04-quick-start-guide.md
source/documentation/06-api-reference.md
source/documentation/10-switching-to-production.md

We shouldn't use "login" or "log in" as a verb: https://www.gov.uk/guidance/style-guide/a-to-z-of-gov-uk-style#sign-in-or-log-in

Removes instances of login as verb

---

source/documentation/04-quick-start-guide.md
source/documentation/05-payment-overview.md
source/documentation/06-api-reference.md
source/documentation/07-integration-details.md
source/documentation/08-refunding-payments.md

All documentation links are pointing to 1.0.1 which has been deprecated by v1.0.2.
There is also no documentation specifying the expected values for the different payment type states when searching for a payment when using the api.
The payment states can be found when viewing https://govukpay-docs.cloudapps.digital/#payment-status-lifecycle, but should also be linked to in the example column for state in the gelato documentation.
The card type values can be found when viewing https://docs.payments.service.gov.uk/#card-types, but should also be linked to in the example column for card_brand in the gelato documentation.
solo @belindac

Support #2788803 Updating documentation

---

source/documentation/10-switching-to-production.md

We are updating merchant details to organisation details in the admin tool. 
This is because Worldpay calls credentials ’Merchant credentials‘ which is confusing for users.

Update merchant details

---

source/documentation/04-quick-start-guide.md

Removes "at left" altogether; it's on the left, and some of the language is superfluous anyway.

Removes erroneous content

---

source/documentation/05-payment-overview.md

Saying "something like this" doesn't sound good.

Cleans up language re. 'Enter card details' page

---

source/documentation/14-security.md

@katiebates commented that:
> for looking up individual payments, this is true, but you can also search transactions by email address, card brand, from/to date, reference and state. also soon you'll be able to search by last 4 digits (and cardholder name), since we do store this info.
For this reason, I recommend the best change as far as this [section of the] documentation is concerned is to remove the line with incomplete information.
Unless we do need to add all of this. Once I can add Katie as a reviewer I'll need to add her to review this.

Remove incomplete information for sake of clarity

---

source/documentation/07-integration-details.md

* Removes this line:
> This will soon be fixed as part of the beta.
^ we don't have this on the backlog to fix so it's not accurate
* Adds this line:
> They will have to return to the service retry the payment.

Payment journey language changes

---

source/documentation/06-api-reference.md

Updated documentation (section API rate limits) to reflect rate limits being applied for HTTP POST and GET requests.

Update documentation - API rate limits

---

Gemfile
Gemfile.lock
config/tech-docs.yml

This is testable at https://govukpay-docs-test.cloudapps.digital/
This hasn't yet been published to Rubygems and should still be considered an experimental feature. There are still outstanding issues concerning the indexing of section titles (try searching "Payment links") for example. 
Nonetheless, if we are continuing with multi-page then we should have a search function. 
For further context, contract work has recently been completed on the tech docs tool: this is what has given us multi-page, search, and upcoming API reference functionality. 
We need to use an experimental Gemfile to get search until a new version is published to Rubygems, which should happen soon. (See changes to the Gemfile in this PR).

Adds search in Gemfile and config

---

source/documentation/15-contribute.md

- 'MIT License' is a proper noun and should be treated in US English
- The MIT License link shouldn't go to a Wikipedia page: in this case we shouldn't actually need to link to a generic page and it would be far better if we could link to our actual licence 
- 'Open source' should not be capitalised and should be hyphenated when used as compound adjective
- We shouldn't use "email us" as a link; it should be spelled out fully per GOV.UK style 
- The header 'Open-source components on GOV.UK Pay' gets the point across better
- Other minor language changes

Style/language changes in 'Contribute' page

---

source/documentation/14-security.md

Found a typo when going through Security section of docs 
Fix for the typo (adds word "Pay")

Typo (missing word "Pay")

---

source/documentation/16-support-contact-and-more-information.md

Proposal to simplify the information in the 'support' section. Much of this is duplicated unnecessarily from what's sent to partners when they sign on, some is incorrect or outdated, and some doesn't conform to our house style.

Simplify support information

---

source/documentation/support-contact-and-more-information.md

After the recent support changes, an old bug with a table not rendering properly came up.
A workaround/fix to this. Also the status page isn't rendering as a linked URL so I've embedded it in a link. 
As of right now: https://docs.payments.service.gov.uk/support_contact_and_more_information/#incident-severity

Fix support table not rendering

---

source/case_studies/index.html.md.erb
source/documentation/case-studies.md

Removes the case studies section. I've been through the links in the rest of the documentation and haven't found any links to this, so this should be sufficient. I've also built this locally to test, and nothing breaks. 
Removes the files in the docs that render as the case studies section.

Remove 'case studies' section

---

source/documentation/about-govuk-pay.md
source/documentation/api-reference.md
source/documentation/before-you-start.md
source/documentation/payment-flow-overview.md
source/documentation/quick-start-guide.md
source/documentation/security.md
source/documentation/versioning.md

There are discrepancies in naming ("Pay", "GOV.UK Pay", "The GOV.UK Pay platform" etc.). It should be "GOV.UK Pay" throughout. 
Attempt to standardise to "GOV.UK Pay".

Attempt to standardise naming to GOV.UK Pay throughout

---

source/optional_features/index.html.md.erb

Searching for things under the new "Optional Features" section (for example "Welsh") indexes the wrong section 
A fix for the title

Fixes title of Optional Features section

---

source/documentation/delayed_capture.md

The new delayed capture content in the optional features section needed some minor changes to bring it in line stylistically with the rest of the docs. Some interface text needed emboldening. 
Removes some small passive language parts and amends an interface text section to bold

Minor language changes in delayed capture

---

source/documentation/security.md
source/documentation/testing-govuk-pay.md

@tillwirth asked me to specify in the documentation that it's possible to use HTTP with sandbox accounts when making payments.
First attempt at restructuring some parts of the documentation to reflect the above request, mindful that we still enforce HTTPS for live accounts.
Needs review from the product side and/or tech side to verify the language makes sense.

First attempt at drafting some content on not needing HTTPS for sandbox

---

source/taking_payments/index.html.md.erb

A quick fix to rename the "Integration details" section to 'Making payments'. In the long run we'll likely revisit this section but for the time being @heathd and @tillwirth concluded (and I concur) that "Integration details" isn't an appropriate title for the section 
Renames to "Making payments" and removes preamble section

Renames integration details section

---

source/index.html.md.erb

A new landing page for the technical documentation (i.e. where users end up when they first see it, unless they're following a specific link). Instead of the "About GOV.UK Pay" page, which I highly doubt anybody reads, they are now linked to the more appropriate (and more regularly maintained) features page on GOV.UK and in this page they are now given a simple description about the platform and what it does in case they end up on the docs first as part of their user journey - this is relatively unlikely but worth accounting for. The landing page also now offers an explanation of how to navigate through the technical documentation. 
Almost entirely new landing page 
Use the rich text preview to see how this would appear in situ

New landing page for documentation

---

source/switching_to_live/index.html.md.erb

Better signposting for landing page for 'Switching to live'. 
Slight changes to language to make it more obvious that people can use the left-hand navigation bar to find information on different live gateways. 
https://docs.payments.service.gov.uk/switching_to_live/#switching-to-live

Better signposting in 'Switching to live' landing page

---

source/payment_links/index.html.md.erb

Adds link to payment links product page in the relevant section in the docs
https://docs.payments.service.gov.uk/payment_links/#payment-links
https://www.payments.service.gov.uk/payment-links/

Link to payment links product page 

---

source/troubleshooting/index.html.md.erb

I'd like to review this section as a whole but for now this is accounting for the first part of https://payments-platform.atlassian.net/browse/PP-4206
Adds these two lines to reasons why a user might get a P0920 error:
+ you have not included a ``Content-Type: application/json`` header
+ you've used an ``Accept`` header but with something other than ``application/json``
https://payments-platform.atlassian.net/browse/PP-4206

Adds some extra troubleshooting lines

---

source/switching_to_live/before_you_switch_to_live/index.html.md.erb

The engagement team reported that a user got confused about needing a contract before switching to live, so we should add a line about that. Also, currently, the 'Before you switch to live' link is appearing quite far down in the left-hand nav rather than near the top. 
Fix appearance of 'Before you switch to live' in left-hand nav, and adds line about needing contract.

Minor improvements to 'Switching to live' section

---

source/before_you_start/index.html.md.erb
source/testing_govuk_pay/index.html.md.erb

The "Before you start" section breaks GOV.UK style slightly, in places. 
Separately, I'm also not entirely convinced we actually need this section. I've proposed moving some of the content to the "Testing" section in this PR, but we could move the rest of the content to the landing page and more strongly emphasise the features/product page on that. I'm not sure about having an explicit "Integration" section. 
I would also suggest that we either rename the "Quick start guide" section to "API quick start guide" (or at least better reflect that that section is specifically about using the API) or that we rework that section to make it more generalised than just the API. 
1. Moves some of the content from "Before you start" to the "Testing GOV.UK Pay" section. The content in question is about …

Improve "Before you start" section and add information about payment links

---

source/refunding_payments/index.html.md.erb
source/reporting/index.html.md.erb

Getting some information about searching for refunds with the /refunds endpoint in the public documentation
Improves some language in refunding before a proper revamp, adds notes about refunding to reporting page, adds notes about searching for refunds with the API
Live preview: https://govukpay-refund-revamp.cloudapps.digital/refunding_payments/#refunding-payments

Improves 'Refunds' section, adds note about searching for refunds with the API, adds note about refunds to 'Reporting' section

---

source/refunding_payments/index.html.md.erb
source/reporting/index.html.md.erb

The same rogue parenthesis appears in the reporting and refunding API call examples 
Removes rogue ")" from examples where appropriate

Rogue parenthesis (multiple times)

---

source/api_reference/index.html.md.erb

Mark and Karl have produced better content than what we have to describe API errors 
Adds Mark/Karl's error messages content, but changes the presentation of it in the docs to accommodate it. I've had to be a little bit creative. 
https://govukpay-apierrors.cloudapps.digital/api_reference/#api-errors-caused-by-payment-statuses

adds new error message text, simplifies presentation

---

source/reporting/index.html.md.erb

Makes clear users can have reporting for each service they have set up in GOV.UK Pay 
Single-line change to reflect above

Makes clear reporting is for each service

---

source/payment_flow_overview/index.html.md.erb

Adds Design System components and a warning symbol to prove it works (it's appropriate to have one here rather than a blockquote, as we're currently using), in the payment flow section 
Follows https://github.com/alphagov/govuk-frontend/blob/master/docs/installation/installing-from-dist.md
https://govukpay-designsystem.cloudapps.digital/payment_flow_overview/#payment-flow

adds warning symbol 

---

source/switching_to_live/before_you_switch_to_live/index.html.md.erb
source/switching_to_live/set_up_a_live_epdq_account/index.html.md.erb
source/switching_to_live/set_up_a_live_smartpay_account/index.html.md.erb
source/switching_to_live/set_up_a_live_worldpay_account/index.html.md.erb

The documentation for 'Switching to live' currently directs people to use the old 'Switch service' pattern in the banner for the self-service tool; this has been changed to 'My services'. This was highlighted in https://govuk.zendesk.com/agent/tickets/3441245
Changes in the relevant section of the docs to reflect the new state. I can't see any other sections of the docs where this needs changing but please let me know if you find any.

Changes 'Switch service' to 'My services'

---

source/optional_features/index.html.md.erb

The optional features list in the tech docs isn't an exhaustive list of Pay's optional features, but the current line of text implies that inadvertently 
☝️ suggestion to amend this

adjusts note about optional features

---

source/api_reference/index.html.md.erb
source/contribute/index.html.md.erb
source/index.html.md.erb
source/making_payments/index.html.md.erb
source/optional_features/corporate_card_surcharges/index.html.md.erb
source/optional_features/delayed_capture/index.html.md.erb
source/payment_flow/index.html.md.erb
source/quick_start_guide/index.html.md.erb
source/refunding_payments/index.html.md.erb
source/security/index.html.md.erb
source/switching_to_live/set_up_a_live_epdq_account/index.html.md.erb
source/switching_to_live/set_up_a_live_smartpay_account/index.html.md.erb
source/switching_to_live/set_up_a_live_worldpay_account/index.html.md.erb
source/testing_govuk_pay/index.html.md.erb
source/troubleshooting/index.html.md.erb
source/versioning/index.html.md.erb

We should use proper conventions for section title links (bold), curly quotes rather than straight ones to match other Pay content where appropriate (not in API responses), and set a placeholder convention
Uses __bold__ for section title links, curly quotes (” and ‘ rather than " and ') and sets placeholder convention `<THIS-IS-A-PLACEHOLDER>`

Section title conventions, curlification, placeholders

---

source/account_structure/index.html.md.erb
source/api_reference/index.html.md.erb
source/contribute/index.html.md.erb
source/index.html.md.erb
source/making_payments/index.html.md.erb
source/optional_features/corporate_card_surcharges/index.html.md.erb
source/optional_features/custom_branding/index.html.md.erb
source/optional_features/delayed_capture/index.html.md.erb
source/optional_features/index.html.md.erb
source/optional_features/welsh_language/index.html.md.erb
source/payment_flow/index.html.md.erb
source/payment_links/index.html.md.erb
source/quick_start_guide/index.html.md.erb
source/refunding_payments/index.html.md.erb
source/reporting/index.html.md.erb
source/security/index.html.md.erb
source/support_contact_and_more_information/index.html.md.erb
source/switching_to_live/before_you_switch_to_live/index.html.md.erb
source/switching_to_live/index.html.md.erb
source/switching_to_live/set_up_a_live_epdq_account/index.html.md.erb
source/switching_to_live/set_up_a_live_smartpay_account/index.html.md.erb
source/switching_to_live/set_up_a_live_worldpay_account/index.html.md.erb
source/testing_govuk_pay/index.html.md.erb
source/troubleshooting/index.html.md.erb
source/versioning/index.html.md.erb

There are a lot of trailing whitespaces in `index.html.md.erb` files we use to render our docs. This isn't good practice even though it's not actually important as far as Middleman's rendering is concerned, because it may be awkward for some people navigating through the docs in future when making edits using Git. 
Rids all docs files of whitespace. 
I've tested and built this locally and can't see any changes as far as the user is concerned. If I've missed something we can revert this commit.

Remove trailing whitespace in all index.html.md.erb files

---

source/switching_to_live/set_up_a_live_smartpay_account/index.html.md.erb

Per feedback from FCO, we need to amend the order of information in our Smartpay switching to live docs: we should direct users to generate an encryption key BEFORE saving roles/accounts configuration
Switches section on using encryption key and section on saving configuration around, so that encryption comes first
ZenDesk ticket 3483808

Amendment to 'Switching to live' Smartpay docs re. generating encryption key before saving roles/accounts configuration

---

source/optional_features/index.html.md.erb
source/optional_features/use_your_own_error_pages/index.html.md.erb

Introduction of 'Custom error pages' content (directly redirect) 
Adds 'Custom error pages' content in 'Optional features' section
In the first instance I'd just like to know whether this is on the right lines and whether we need to do anything else. I can rebase or `--reset soft` and amend the commits after to ensure it's only one commit that goes into the main repo when this is done. Also, I'll need to have this writer-reviewed.

'Use your own payment failure pages'

---

source/payment_flow/index.html.md.erb

The 'Payment flow' section breaks style in some places
Language amendments/tidying for 'Payment flow' section
@katiebates does the 'Resume payments' section contradict the 'Use your own payment failure pages' guidance slightly?

Language amendments to 'Payment flow' section

---

source/switching_to_live/index.html.md.erb
source/switching_to_live/set_up_a_live_worldpay_account/index.html.md.erb

We haven't had access to the user journey for switching to live on Worldpay until now, so there are some inaccuracies in the documentation. It seems like Worldpay may have amended/updated some terminology, as well. Also, we should be recommending __New Username__ above __Original XML Username__. 
Amends Worldpay STL documentation to reflect actual user journey/Worldpay updates

Worldpay docs inaccuracies 

---

source/quick_start_guide/index.html.md.erb

Erroneous double quote in QS guide section

---

source/optional_features/delayed_capture/index.html.md.erb

The delayed capture should reflect a 48 hour expiry 
Change to reflect above need

Change notes about 90min expiry to 48h in delayed capture 

---

source/quick_start_guide/index.html.md.erb

An easy addition to call out the need to sign up for the API explorer as part of the QS guide
Adds a line and a link to Gelato

Calls out need to sign up for API explorer in QS guide

---

source/account_structure/index.html.md.erb
source/api_reference/index.html.md.erb
source/payment_flow/index.html.md.erb
source/quick_start_guide/index.html.md.erb
source/refunding_payments/index.html.md.erb

Most of our images 404 at the moment in the docs if actually selected/clicked on; this is because they're not pointing to the correct path 
Point images (where wrong) to correct path

Adds correct images path to avoid 404s

---

source/payment_flow/index.html.md.erb

@tillwirth pointed out that we have two sections on resuming payments, via email. I don't honestly know how this happened, but I've consolidated them in this PR. 
Consolidation of two sections which contain information about the same subject.

Combines two 'resume payments' sections

---

source/api_reference/index.html.md.erb

@tillwirth pointed out via email that we lack 'Maestro' in https://docs.payments.service.gov.uk/api_reference/#card-types
Adds Maestro to list of cards in API reference section
This isn't my area of expertise so I don't know that my proposed edit at time of writing is correct, so I'm opening this as a pointer that this change is needed as much as anything

Adds Maestro

---

source/account_structure/index.html.md.erb
source/api_reference/index.html.md.erb
source/contribute/index.html.md.erb
source/making_payments/index.html.md.erb
source/optional_features/corporate_card_surcharges/index.html.md.erb
source/optional_features/delayed_capture/index.html.md.erb
source/payment_flow/index.html.md.erb
source/quick_start_guide/index.html.md.erb
source/refunding_payments/index.html.md.erb
source/reporting/index.html.md.erb
source/switching_to_live/set_up_a_live_epdq_account/index.html.md.erb
source/switching_to_live/set_up_a_live_smartpay_account/index.html.md.erb
source/testing_govuk_pay/index.html.md.erb
source/versioning/index.html.md.erb

Before I leave the project, I'm going through everything to make sure I've not left any broken links/inconsistencies etc.
* introduces a break between the 'Quick start guide' title and the warning that appears about storing API keys securely
* uses the term "admin *tool*" throughout (rather than "admin site") 
* uses bold formatting for interface text rather than quotes, e.g. linking to other sections 
* adds "[external link]" where appropriate
* small style edits, e.g. missing full stops
This excludes changes made to the **Security** section in https://github.com/alphagov/pay-tech-docs/pull/234 and the **Making payments** section in https://github.com/alphagov/pay-tech-docs/pull/222

Style amendments across docs

---

source/security/index.html.md.erb

The 'Security' section breaks style in some places and lacks a warning symbol where a blockquote is used 
Amendments to the 'Security' section so that it's tonally consistent with the newer version of the Pay documentation, and does not break GOV.UK style 
Note for reviewer: I've left my own review comments to be addressed by SME before merge

Style amendments to 'Security' section

---

source/api_reference/index.html.md.erb

@tillwirth wrote via email:
> The following section/statement is no longer accurate: 
> https://docs.payments.service.gov.uk/api_reference/#use-the-admin-tool
> "Select a payment with a "failed", "cancelled" or "error" status."
> We have replaced the "failed" state with "new" states that only exist in the admin tool but not the  API: Declined and Timed Out. We may have also combined the "user cancelled" and "system cancelled" into one "cancelled" state in the admin tool but I'm not sure about that. 
I confirmed that the "cancelled" statuses are indeed consolidated in the self-service tool 
Suggested edit to account for the above

Amend description re. payment status failure in admin tool 

---

source/index.html.md.erb

We shouldn't use FAQs anywhere on GOV.UK
Removes FAQ and changes to different, statement-based format

Removes FAQ format from landing page

---

source/account_structure/index.html.md.erb
source/api_reference/index.html.md.erb
source/contribute/index.html.md.erb
source/integrate_with_govuk_pay/index.html.md.erb
source/making_payments/index.html.md.erb
source/optional_features/corporate_card_surcharges/index.html.md.erb
source/optional_features/custom_branding/index.html.md.erb
source/optional_features/delayed_capture/index.html.md.erb
source/optional_features/index.html.md.erb
source/optional_features/use_your_own_error_pages/index.html.md.erb
source/payment_flow/index.html.md.erb
source/payment_links/index.html.md.erb
source/quick_start_guide/index.html.md.erb
source/refunding_payments/index.html.md.erb
source/reporting/index.html.md.erb
source/security/index.html.md.erb
source/support_contact_and_more_information/index.html.md.erb
source/switching_to_live/before_you_switch_to_live/index.html.md.erb
source/switching_to_live/index.html.md.erb
source/switching_to_live/set_up_a_live_epdq_account/index.html.md.erb
source/switching_to_live/set_up_a_live_smartpay_account/index.html.md.erb
source/switching_to_live/set_up_a_live_worldpay_account/index.html.md.erb
source/testing_govuk_pay/index.html.md.erb
source/troubleshooting/index.html.md.erb

The bullet points and numbered steps in the docs aren't currently uniform. In the Markdown itself, we use "+", "-", "*"
Some bullets have spaces and some don't. I think it's easiest (and clearest) if we just have spaces everywhere. 
Makes all bullets use "*"
Adds spaces between all numbered steps and bullets
Other very few, very minor edits I spotted along the way 
Would be good to have someone review this properly to assess whether my suggested changes make sense, and to make sure I haven't broken up any bullets/steps

Make bullets/steps uniform

---

source/payment_flow/index.html.md.erb

HMPO feedback on the documentation states that it would be useful to say that a Number is required for the parameter "amount" when Posting to the /payments endpoint.
Add statement to the Payment flow overview section that the amount parameter is a number data type.
This is a small change based on HMPO feedback and just needs review and approval from a Pay approved reviewer.

State that the amount is a number

---

source/api_reference/index.html.md.erb
source/integrate_with_govuk_pay/index.html.md.erb
source/making_payments/index.html.md.erb
source/optional_features/delayed_capture/index.html.md.erb
source/optional_features/use_your_own_error_pages/index.html.md.erb
source/payment_flow/index.html.md.erb
source/quick_start_guide/index.html.md.erb
source/refunding_payments/index.html.md.erb
source/reporting/index.html.md.erb
source/versioning/index.html.md.erb

We're moving away from Gelato, to Slate, for the "endpoint" part of our API documentation offering. We need to remove references to it, and to an "API explorer" generally. We also need to change some surrounding text, where relevant, particularly in the Quick start guide. The Slate instance is here:
https://govukpay-api-browser.cloudapps.digital/
@jonathanglassman and I have been through and changed the docs to satisfy the above. We refer to the new Slate instance as the "API browser". 
This should be reviewed by others because it involves a lot of changes and we need to make sure they make sense, and that the links work. @jonathanglassman and I have reviewed together and we're happy that it's OK, but it's important to get this right. Ideally @heathd or @alexbishop1 will review to confirm …

Change docs to reflect new Slate instance rather than Gelato

---

source/account_structure/index.html.md.erb
source/optional_features/custom_branding/index.html.md.erb
source/testing_govuk_pay/index.html.md.erb

Remove gaps in heading hierarchy to comply with accessibility requirements.
All documentation websites must meet the new public sector requirement to be more accessible. The website meets this requirement if it complies with the international WCAG 2.1 AA accessibility standard.
The GOV.UK Pay (and other) tech docs mostly meet this requirement already. However, one of the requirements is that the heading structure cannot miss levels i.e. you cannot follow an H1 with an H3, or an H2 with an H4. I've audited the Pay tech docs content to see if this occurs anywhere and proposed some changes to rectify this.
Corrected all instances of headings skipping levels. 
Check that the changes do not make the tech docs any less useful for the user.

Amend heading structure to comply with accessibility requirements

---

source/making_payments/index.html.md.erb
source/payment_flow/index.html.md.erb

The minimum transaction value is one pence or £0.01. It is possible to have a transaction value of £0.00, however this is not a feature that we want to publicise. 
The tech docs do not currently state this minimum transaction value.
Add content stating that minimum payment amount is one pence.

Add content stating that minimum payment amount is one pence.

---

source/integrate_with_govuk_pay/index.html.md.erb

If you turn off your service's collection of billing addresses, this might cause your service's integration with GOV.UK Pay to break.
Add content stating the issue that may arise if you stop collecting your users' billing addresses.

Disable billing address collection 

---

source/stylesheets/screen-old-ie.css.scss
source/stylesheets/screen.css.scss

Add whitespace `&nbsp;` between the `Worldpay` link and the title `The differences between test and live accounts`, because the CSS of the title makes the link un-clickable.
Avoided CSS changes not to break other pages in terms of displaying titles.
with @jonheslop

PP-4764 Make Worldpay link clickable

---

source/switching_to_live/set_up_a_live_worldpay_account/index.html.md.erb

Worldpay merchants must contact their relationship manager to enable American Express cards with Worldpay before those cards start working.
The process differs slightly depending on whether the merchant is Crown or non-Crown.
Add content that states that Worldpay merchants must contact their relationship manager to enable American Express cards with Worldpay before those cards start working

Add content on enabling Amex cards

---

source/making_payments/index.html.md.erb

Commit 0389a5c750fa170072a973afcc7daa61837cae12 changed the content of the ‘Making payments’ section. Unfortunately, some information was removed or put in a place where it doesn’t make as much sense. Some of the warnings are inaccurate and we’ve been contacted by confused service users.
- Move `return_url` content back near the beginning of the ‘Making payments` section.
- Add back content about the `next_url`.
- Stop warning that the payment ID should be kept secret. It doesn’t need to be (we include it in payment page URLs). However, keep some content about the `next_url` being sensitive.
- In the ‘Choose the return URL and match users to payments section, add a warning that the mechanism used to match returning users to payments should be tamper-proof (e.g. by not putting the payment …

Small clarifications to the ‘Making payments’ section

---

source/switching_to_live/set_up_a_live_epdq_account/index.html.md.erb
source/switching_to_live/set_up_a_live_smartpay_account/index.html.md.erb
source/switching_to_live/set_up_a_live_worldpay_account/index.html.md.erb

There have been some support tickets where payments have failed and users have not been able to figure out why. These changes clarify the most common reason why payments fail.
Add content on checking that:
- your credentials on gov.uk pay are correct
- you have set up notifications that enable features like refunds correctly

Add content into the "Test your configuration" sections.

---

source/testing_govuk_pay/index.html.md.erb

Our mock card numbers content needs clarifying as per some user feedback we have received.
- Adds missing mock card numbers
- Removes unnecessary and confusing links to PSP content
- Clarifies that you must use test card numbers with a test account

Update testing with new mock card numbers

---

source/switching_to_live/before_you_switch_to_live/index.html.md.erb

One of the links is missing a ")". This means that it is not a link.
Add the missing ")" to make the link a link again
Accept the PR :-)

Add missing )

---

source/optional_features/custom_branding/index.html.md.erb

You can use custom branding on all pages in your payment journey.
Not just the 'payment pages' (Enter card details, Confirm your payment pages) but also any pages associated with a payment link (eg enter your reference, payment amount page).
Clarify that custom branding applies to all pages in your payment journey, not just payment pages, and also applies regardless of whether you integrate or use payment links.

Update custom branding pages

---

source/direct_debit/index.html.md.erb

First link in https://docs.payments.service.gov.uk/direct_debit/#get-started is incorrect.
Correct link by adding a `/` at the start.

Correct link to contact support section

---

source/security/index.html.md.erb

The product security page at https://www.payments.service.gov.uk/security/ will have a reference to the cloud security principles.
Add a reference to the NCSC page on implementing the cloud security principles to the security section.

Add reference to NCSC cloud security principles to the Security section

---

source/optional_features/custom_branding/index.html.md.erb

When services want custom branding on emails, we set them up with a Notify account. In the Notify account a reply-to email address needs to be specified. This can be the (new) generic gov.uk pay no reply address (gov.uk-pay-no-reply@digital.cabinet-office.gov.uk) but it's a better user experience if the service actually provide their own, so then users can go directly back to the service.
Add content to state that services can set up a reply-to email address for their custom branded emails, and if they don't, that email address will default to the GOV.UK Pay no reply email address.

add reply-to email address content to custom branding page

---

source/testing_govuk_pay/index.html.md.erb

There's a broken link to mock card numbers in the second paragraph of https://docs.payments.service.gov.uk/testing_govuk_pay/#testing-gov-uk-pay.
Fix the broken link.

Fix link to mock card numbers

---

source/integrate_with_govuk_pay/index.html.md.erb
source/optional_features/custom_metadata/index.html.md.erb
source/optional_features/digital_wallets/index.html.md.erb
source/optional_features/index.html.md.erb
source/optional_features/use_your_own_error_pages/index.html.md.erb

Service teams can:
- add custom metadata to payments using API calls
- retrieve the metadata using API calls or the GOV.UK Pay admin tool
Add new content about how to add and retrieve custom metadata.

Custom metadata

---

source/optional_features/index.html.md.erb
source/optional_features/prefill_user_details/index.html.md.erb
source/payment_flow/index.html.md.erb

When service teams create a payment through the API, they can provide user details that they've already collected in their service. This will then prefill fields on the payment page. 
Add a new page about prefilling fields, and a link from the 'Payment flow' page.
Please review for factual accuracy.

Prefill fields on the payment page

---

source/index.html.md.erb
source/refunding_payments/index.html.md.erb
source/reporting/index.html.md.erb

Service teams using GOV.UK's Payment Service Provider (PSP) can retrieve information about transaction fees using API calls or the GOV.UK Pay admin tool. 
Add new content about how to add and retrieve transaction fee information.

Transaction fee information through API

---

source/api_reference/index.html.md.erb
source/making_payments/index.html.md.erb
source/optional_features/delayed_capture/index.html.md.erb
source/optional_features/digital_wallets/index.html.md.erb
source/optional_features/use_your_own_error_pages/index.html.md.erb
source/payment_flow/index.html.md.erb
source/quick_start_guide/index.html.md.erb
source/refunding_payments/index.html.md.erb
source/reporting/index.html.md.erb
source/security/index.html.md.erb

It's no longer GOV.UK style to add "[external link]" after external links in tech docs.
Remove "[external link]" everywhere it appears.

Remove "[external link]" from external links

---

source/payment_flow/index.html.md.erb
source/refunding_payments/index.html.md.erb

We're missing documentation for Stripe users about:
- how payments will show on the merchant's bank account
- how refunds will be taken
Added documentation about both of the above to the 'Payment flow' and 'Refunding payments' pages respectively.
I've also rejigged the 'Refunding payments' page to collect together 'What happens next' documentation in one section.
Please review for factual accuracy.

Add documentation about Stripe refunding and payment description

---

source/making_payments/index.html.md.erb
source/payment_flow/index.html.md.erb

We're missing the maximum transaction limit in the documentation about making payments.
- Add the transaction limit to documentation about creating a payment
- Move API call detail and example from the Payment flow page to the Making payments page - to avoid content duplication and better meet the user need on each page
- Quick tweak to the `description` in the examples so it's clearer this value will be shown to end users
Please review for factual accuracy.

Add maximum transaction limit

---

source/optional_features/prefill_user_details/index.html.md.erb

We're missing the character limits for the API request parameters in https://docs.payments.service.gov.uk/optional_features/prefill_user_details/. 
Add the character limit for each parameter.
Please check if the changes are factually correct.

Add character limits for parameters when prefilling fields

---

source/troubleshooting/index.html.md.erb

There's a stray quote mark on the Troubleshooting page because of incorrect markdown around `bearer`.
Fix the markdown around `bearer`, and remove the mention of quote marks (as these now don't appear).

Fix markdown on `bearer` on Troubleshooting page

---

source/api_reference/index.html.md.erb

The Direct Debit API error codes are incorrect on https://docs.payments.service.gov.uk/api_reference/#api-error-codes.
Update https://docs.payments.service.gov.uk/api_reference/#api-error-codes to remove unused error message P1000, and change P1001 to P1103.
Please check factual accuracy.

Fix Direct Debit error codes

---

source/direct_debit/index.html.md.erb

Quick fix to remove unnecessary whitespace above the '## Mandate statuses' and '## Payment statuses' tables on https://docs.payments.service.gov.uk/direct_debit/
Remove the `<br>` tags above the tables to remove the whitespace.

Fix whitespace above tables on Direct Debit pages

---

source/reporting/index.html.md.erb

Teams who have Worldpay as their PSP can use `capture_submit_time` and `capture_date` from the API GET response to find out when Worldpay took a payment, to help them reconcile.
Update the 'Reporting' page to include content about `capture_submit_time` and `capture_date`.
Please check factual accuracy.

Add content on capture_submit_time and capture_date 

---

source/integrate_with_govuk_pay/index.html.md.erb

For users who are turning on/off the collection of billing addresses, it's useful to know that you can prefill fields on the payment page - as this avoids end users having to enter their billing address twice.
Add a link from ## Collecting your users’ billing addresses to the 'Prefilling fields on the payment' 
Please check for factual accuracy.

Add prefilling fields to the billing address section

---

source/api_reference/index.html.md.erb
source/optional_features/delayed_capture/index.html.md.erb

We've added a `capturable` status to the get payments API, which shows that a [delayed capture](https://docs.payments.service.gov.uk/optional_features/delayed_capture/#delayed-capture) payment is ready for capture.
Add the `capturable` status code to the API reference page and the Delayed capture pages in the documentation.

Add 'capturable' status for delayed capture payments

---

source/direct_debit/index.html.md.erb

We've changed some of the `status` codes that are sent by the API when teams request information about Direct Debit mandates and payments. We've also removed the `finished` state.
Update the https://docs.payments.service.gov.uk/direct_debit/#mandate-statuses and https://docs.payments.service.gov.uk/direct_debit/#payment-statuses tables in our documentation, and clarify indemnity claims.

Update documentation on Direct Debit mandate and payment statuses

---

source/testing_govuk_pay/index.html.md.erb

The 5101180000000007 card is a prepaid unknown credit card; as its unknown no
corporate surcharge will be applied.

zd3764984: Update test corporate credit card

---

source/switching_to_live/set_up_a_live_worldpay_account/index.html.md.erb

The list of events that teams need to check when they're setting up WorldPay 'Merchant Channel' has some unneeded events.
Update the ['Merchant Channel' events list](https://docs.payments.service.gov.uk/switching_to_live/set_up_a_live_worldpay_account/#set-up-merchant-channel) to remove the events that teams no longer need to select.
Please check for factual accuracy.

Remove unneeded items from 'Merchant Channel' events list

---

source/direct_debit/index.html.md.erb

Remove 'From August 2019' from the Direct Debit documentation page, as we're now into August.

Remove 'From August 2019' on Direct Debit page

---

source/api_reference/index.html.md.erb

It's recommended that teams use a web proxy to allow traffic to our API through a secure network. We do not support firewall whitelists of IP addresses (there's more on this in technology blog post about [a whitelisting approach for cloud APIs](A whitelisting approach for cloud APIs)). 
Update https://docs.payments.service.gov.uk/api_reference/ with information about using a web proxy and avoiding firewall whitelists.

Add documentation about setting up a proxy

---

source/optional_features/digital_wallets/index.html.md.erb

The https://docs.payments.service.gov.uk/optional_features/digital_wallets/ documentation page is out of date. Teams can enable digital wallet functionality through the admin tool.
Remove references on https://docs.payments.service.gov.uk/optional_features/digital_wallets/ to the feature being invitation-only and in private beta.
(There are also 2 tiny fixes to whitespace at the end of lines elsewhere on the page.)
Check if factually correct.

Update digital wallets documentation

---

source/api_reference/index.html.md.erb

We're missing the P1000 error code from our list of API error codes. It occurs when a team tries to collect a payment with a `paymentId` that we don't recognise.
Add the P1000 error to https://docs.payments.service.gov.uk/api_reference/#api-error-codes.

Add P1000 error to list of API error codes 

---

source/reporting/index.html.md.erb

We're missing full stops at the end of the bullets in the https://docs.payments.service.gov.uk/reporting/#manual-reporting section.
Add full stops.

Fix full stops on bullets in 'Manual reporting'

---

README.md

We need to remove the recently-added 'Release' section from the Readme, as it's about the Pay tech docs in particular - rather than downloading and using the Tech Docs Template generally.

Remove release section from README

---

source/direct_debit/index.html.md.erb
source/reporting/index.html.md.erb

When you search for payments by `reference` using the API, the parameter now needs to be an exact match, rather than a partial string.
Update the Reporting and Direct Debit pages to update `reference`, and clarify as a whole which parameters are case sensitive or exact match only.

Update `reference` parameter in documentation about searching for payments

---

source/quick_start_guide/index.html.md.erb
source/security/index.html.md.erb
source/switching_to_live/index.html.md.erb
source/testing_govuk_pay/index.html.md.erb

We're improving the documentation for developers testing GOV.UK Pay, to make it more user-focused and concise.
General improvements to the content on https://docs.payments.service.gov.uk/testing_govuk_pay/, to:
- clarify integration testing and which accounts to use
- remove the mock payment section
- rename the page to 'Testing your integration' so it better reflects the content
- remove the link on the security page (as clicking through doesn't provide users with more information about using http instead of https on their test account)
Please check everything's factually accurate.

Improve testing documentation

---

config/tech-docs.yml

Adding a link to the GOV.UK Pay accessibility statement in the footer of the technical documentation.

Add link to accessibility statement

---

source/api_reference/index.html.md.erb

We've updated the rate limits for our API to [introduce separate 'buckets' each with their own API limit](https://github.com/alphagov/pay-publicapi/pull/701) 
Update https://docs.payments.service.gov.uk/api_reference/#rate-limits with the new rate limits.

Update API rate limits in documentation

---

source/testing_govuk_pay/index.html.md.erb

We've added a new mock card number for use in testing.
Add Mastercard credit mock card number to https://docs.payments.service.gov.uk/testing_govuk_pay/#mock-card-numbers.

Add Mastercard credit mock card number

---

source/testing_govuk_pay/index.html.md.erb

Add the 4000000000000010 mock card number to the testing docs, which card ID says is a Visa card for which it is unknown whether it is prepaid and for which it is unknown whether it is a credit or debit card but which is not a corporate card.

BAU: Add 4000000000000010 mock card number to testing docs

---

source/api_reference/index.html.md.erb

We're missing API error code P1003, which is used when a delayed capture request is sent but the payment does not have a status of `capturable`.
Add P1003 to https://docs.payments.service.gov.uk/api_reference/#api-reference.
(And fix an unrelated typo in the error codes table.)

Add error code P1003

---

config.rb
config/tech-docs.yml

Activate the tech docs template feature that adds 'contribution' links on each page for users to:
- see the page in our GitHub repo
- report a problem with the page
There's an example of what this looks like at the bottom of any Verify tech docs page, for example the [front page](https://www.docs.verify.service.gov.uk/#gov-uk-verify-technical-documentation).
To do this I've:
- added the relevant flag in the tech docs config file
- added code to config.rb to rewrite the 'report a problem' link so it's a `mailto` rather than a link to create a PR (similarly to [Verify tech docs](https://github.com/alphagov/verify-tech-docs/blob/a0a205c5ebac330c7c510f62929f7d31e2f97be9/config.rb)). This is to help users who want to report feedback without using GitHub.
Please check it all looks ok.

Add feedback and GitHub links to each page 

---

source/api_reference/index.html.md.erb
source/reporting/index.html.md.erb
source/testing_govuk_pay/index.html.md.erb

The [card types table](https://docs.payments.service.gov.uk/api_reference/#card-types) is misleading and a little confusing (and oddly placed in the API reference page), especially now we've implemented `card_type` in payment information in addition to `card_brand`.
- Move the table out of the API reference page into the Reporting page, and include only needed information (including clarifying that the search value is different to the API response value for some card brands)
- Fix incorrect card types in the [mock card numbers table](https://docs.payments.service.gov.uk/testing_govuk_pay/#mock-card-numbers) 

Improve documentation about card brands

---

source/making_payments/index.html.md.erb

We're missing the character limit for the `return_url` parameter in requests to create a payment.
Add the 2,000 character limit for the `return_url` parameter on the [Making payments](https://docs.payments.service.gov.uk/making_payments/#making-payments) page.

Add character limit for return_url

---

source/direct_debit/index.html.md.erb

Clarify who can sign up for the pilot of using the Direct Debit API. This will match an update on https://www.payments.service.gov.uk/direct-debit/, and match the existing mention on that page of this being a pilot.
Update the [Direct Debit](https://docs.payments.service.gov.uk/direct_debit/#direct-debit) page with details and how to contact us to sign up for the pilot.

Update Direct Debit pilot details

---

source/switching_to_live/set_up_a_live_epdq_account/index.html.md.erb
source/switching_to_live/set_up_a_live_smartpay_account/index.html.md.erb
source/switching_to_live/set_up_a_live_worldpay_account/index.html.md.erb

The 'Account credentials' page in the admin tool is changing to 'Your PSP'.
Update our 'Go live' documentation with the new page name.

Update go live docs with new admin tool settings name

---

source/account_structure/index.html.md.erb
source/api_reference/index.html.md.erb
source/index.html.md.erb
source/integrate_with_govuk_pay/index.html.md.erb
source/making_payments/index.html.md.erb
source/optional_features/custom_branding/index.html.md.erb
source/optional_features/custom_metadata/index.html.md.erb
source/optional_features/use_your_own_error_pages/index.html.md.erb
source/optional_features/welsh_language/index.html.md.erb
source/payment_flow/index.html.md.erb
source/payment_links/index.html.md.erb
source/quick_start_guide/index.html.md.erb
source/security/index.html.md.erb
source/support_contact_and_more_information/index.html.md.erb

Our link text for internal links is inconsistent across our technical documentation.
Update internal links so they're consistent, by:
- using verb-noun as far as possible when linking to guidance on doing a task
- using 'our' for links to noun-based pages such as dashboards and references, for example “Read our [API reference]”
- avoiding 'the xxx page' or 'the xxx section'
- avoiding 'refer to the...'
- avoiding 'for more information...' or 'for more details...'
- avoiding 'you may want to read...'
- removing bold
- removing links that did not actually lead to the content they claimed
I've left links in [switching to live](https://docs.payments.service.gov.uk/switching_to_live/#switching-to-live) as they are, because those will be fixed as part of …

Standardise internal links

---

source/reporting/index.html.md.erb

For users looking to download transaction fee information in a CSV file, it's not immediately from the content in https://docs.payments.service.gov.uk/reporting/#psp-fees that 'export' means 'export as a CSV'.
Tweak the content to clarify that you can download as a CSV.

Add 'CSV' keyword to transaction fee download docs

---

config/tech-docs.yml

Description:
- Due to ICO compliance we can't store non-essential cookies so as a temporary measure Google Analytics has been disabled. Re-enable when opt-in has been completed.

PP-5897 Remove Google Analytics Tech Docs

---

source/integrate_with_govuk_pay/index.html.md.erb
source/payment_flow/index.html.md.erb

Teams can now ask us to change what appears on their bank statements if they use Stripe.
Add that teams can ask us to change their bank statement description - and move the content to the Integrating page, as it's most related to the need of reconciling payments.
Please check if factually accurate.

Add guidance on changing bank statement description

---

source/optional_features/welsh_language/index.html.md.erb

Our [Welsh language payment pages](https://docs.payments.service.gov.uk/optional_features/welsh_language/#welsh-language-payment-pages) page suggests we can send Welsh-language emails, which is incorrect.
Tweak content to clarify that teams can contact us if they'd like us to develop this feature in future.

Clarify requesting Welsh emails

---

source/optional_features/delayed_capture/index.html.md.erb
source/payment_flow/index.html.md.erb

The status codes in our [Delayed capture] docs are misleading or ambiguous. We also don't say what status a payment will have if the capture times out.
- Clarify the codes in the error codes table, and make them consistent with the descriptions in the [API reference](https://docs.payments.service.gov.uk/api_reference/#api-reference) page.
- Add the status for expired payments

Clarify delayed capture statuses and error codes

---

Gemfile.lock

Upgrading as the deploy job is failing with
```
Fetching bundler-2.1.3.gem
Successfully installed bundler-2.1.3
1 gem installed
Traceback (most recent call last):
2: from /usr/local/bundle/bin/bundle:23:in `<main>'
1: from /usr/local/lib/ruby/2.7.0/rubygems.rb:294:in `activate_bin_path'
/usr/local/lib/ruby/2.7.0/rubygems.rb:275:in `find_spec_for_exe': Could not find 'bundler' (1.17.2) required by your /tmp/build/80754af9/pay-tech-docs/Gemfile.lock. (Gem::GemNotFoundException)
To update to the latest version installed on your system, run `bundle update --bundler`.
To install the missing version, run `gem install bundler:1.17.2`
```

bau: Use latest version of bundler

---

source/integrate_with_govuk_pay/index.html.md.erb

Replace a table in our [integrating](https://docs.payments.service.gov.uk/integrate_with_govuk_pay/#how-to-integrate-with-the-gov-uk-pay-api) page with a sentence, because the table is inaccessible due to an empty heading cell.

Replace table with empty heading cell

---

config.rb

We're having deployment issues with the documentation since we deployed https://github.com/alphagov/pay-tech-docs/pull/353 to add html-proofer.
Remove html-proofer from the build in `config.rb` for now, so we can restart deployment. We'll then investigate how to re-add html-proofer in a way that doesn't block deployments unexpectedly. 
Please check code updates are ok.

Remove link checking from build

---

source/optional_features/index.html.md.erb

The [optional features](https://docs.payments.service.gov.uk/optional_features/#optional-features) pages is missing a link to blocking prepaid cards. 
Add the link.
Please check the link works.

Add missing link from optional features to blocking prepaid cards

---

source/reporting/index.html.md.erb

The number of transactions teams can export in a CSV file has increased.
Update the maximum value from 10,000 to 100,000.

Increase maximum CSV export rows

---

source/reporting/index.html.md.erb

The [search by card brand table](https://docs.payments.service.gov.uk/reporting/#search-by-card-brand) is displaying incorrectly because of a markdown error.
Fix the table markdown.

Fix incorrect table markdown in card brands table

---

source/switching_to_live/index.html.md.erb

When users create a live account from a test account, certain settings will not be carried over.
Add a new step to the [go live docs](https://docs.payments.service.gov.uk/switching_to_live/) about switching on/off the same settings in your live account as in your test account.

Add documentation about checking account settings during go-live

---

source/api_reference/index.html.md.erb
source/optional_features/index.html.md.erb
source/optional_features/moto_payments/index.html.md.erb

We can now set up a teams' GOV.UK Pay services so they can take MOTO payments (payments by over the phone or by post).
- Add documentation about MOTO payments, including error codes
- Alphabetise the 'Optional feature' page so it's easier to navigate

Add MOTO payments documentation

---

config/tech-docs.yml

We're adding the [Tech Docs Template page expiry notifier](https://github.com/alphagov/tech-docs-monitor) - aka Daniel the Manual Spaniel - to our documentation. The monitor will monitor pages where we've added review metadata, and alert us when a page needs reviewing for factual accuracy.
Update the config file to:
- tell the monitor where to alert us
- not display review banners on docs pages (for now)
Please check the config file looks ok.

Add config for docs review monitoring

---

source/optional_features/custom_metadata/index.html.md.erb

We're changing the way that [custom metadata](https://docs.payments.service.gov.uk/optional_features/custom_metadata/#add-metadata-to-a-payment) is validated, so that strings are case insensitive.
Update the custom metadata page with the change, and tweak the line about unique keys so it better matches the requirements.
I've also added a review date in the metadata (see https://github.com/alphagov/pay-tech-docs/pull/384).

Add case insensitive string requirement to custom metadata docs

---

source/index.html.md.erb

Remove the review date from the front page (as our test with the tech docs monitoring tool is now complete).

Revert "Add review date to front page"

---

source/optional_features/delayed_capture/index.html.md.erb

The table of response codes on the [Delayed capture](https://docs.payments.service.gov.uk/optional_features/delayed_capture/#delayed-capture-of-payments) page is not displaying correctly, due to incorrect markdown. 
Fix the markdown.
Please check it looks right.

Fix table markdown on delayed capture page

---

source/switching_to_live/set_up_a_live_worldpay_account/index.html.md.erb

Some payments are causing errors because they're higher than the 'Maximum transaction limit' in the team's Worldpay settings.
Add setting 'Maximum transaction amount' during the go-live process for Worldpay.

Add setting maximum transaction amount in Worldpay settings

---

source/switching_to_live/set_up_a_live_epdq_account/index.html.md.erb
source/switching_to_live/set_up_a_live_smartpay_account/index.html.md.erb

In our ePDQ and Smartpay go live documentation, we're missing a step about setting up the payment capture method.
Add setting up the payment capture method in the ePDQ and Smartpay go live pages.

Add payment capture method to go-live steps

---

source/testing_govuk_pay/index.html.md.erb

We've seen a couple of instances where teams have tried to test a sandbox account using a real card. 
Add clarification that real cards should not be used in test accounts.

Mention not using real cards in test accounts

---

source/optional_features/delayed_capture/index.html.md.erb

A small tweak to make it clearer when we send confirmation emails for delayed capture payments.
I've also rejigged the paragraph slightly for style and active voice.

Clarify when we send confirmation emails for delayed capture payments

---

source/integrate_with_govuk_pay/index.html.md.erb
source/optional_features/custom_branding/index.html.md.erb
source/optional_features/custom_metadata/index.html.md.erb
source/optional_features/welsh_language/index.html.md.erb
source/payment_flow/index.html.md.erb
source/quick_start_guide/index.html.md.erb
source/switching_to_live/index.html.md.erb

We removed the payment links page, but didn't update the links in the rest of the docs that pointed to it.
Update the links so they point to https://www.payments.service.gov.uk/govuk-payment-pages/
Please check links are ok.

Fix links to payment links

---

README.md
config.rb
source/optional_features/moto_payments/index.html.md.erb

We added a link checker in https://github.com/alphagov/pay-tech-docs/pull/353, but reverted it later due to build issues.
- Re-add `html-proofer` to check links during the tech docs build (this time with a correction to the `url_swap` parameter to correctly remove the domain from links that have it)
- Fixes incorrect links identified by html-proofer in the current content
Please check the changes to `config.rb`, and that the corrected links work.

Re-add link checking with fixed config and links

---

config/tech-docs.yml

We removed the payment links page, but the url is now 404-ing.
Redirect the payment links url to the tech docs homepage.
Please check it works ok.

Fix payment links 404

---

source/index.html.md.erb
source/support_contact_and_more_information/index.html.md.erb

GOV.UK Pay is down for maintenance from 3am to 5am on Tuesday 7 April 2020.
Add downtime message to front page and support page.

Add downtime message

---

source/index.html.md.erb
source/support_contact_and_more_information/index.html.md.erb

The 7 April downtime is complete.
Remove the downtime messages from the front page and the support page.
Please check if all ok.

Remove downtime messages

---

source/reporting/index.html.md.erb

We're missing the `GET /v1/payments/paymentId/events` endpoint in the tech docs (it's including in our Swagger file/[API browser](https://govukpay-api-browser.cloudapps.digital/#gov-uk-pay-api)).
Add documentation on getting payment events to the Reporting page.

Add payment events API endpoint to reporting page

---

source/testing_govuk_pay/index.html.md.erb

Teams should not use fake email addresses when they're trying payments as a user, because it leads to a high email failure rate.
Add dummy email addresses to the [Testing your integration](http://localhost:4567/testing_govuk_pay/#mock-card-numbers-and-email-addresses) page.

Add dummy email addresses for testing

---

source/direct_debit/index.html.md.erb

Service teams can test their Direct Debit integration in their test account by using a mock sort code and account number.
Add a 'Test a mock bank account' section to our [Direct Debit documentation](https://docs.payments.service.gov.uk/direct_debit/#direct-debit).

Add Direct Debit test account details

---

source/making_payments/index.html.md.erb
source/optional_features/index.html.md.erb

Some pages had an identical `weight` in their metadata, which was leading their respective positions in the navigation to be random.
Fix the `weight` for 2 pages so they're no longer identical to 2 other pages.
Please check and merge.

Fix identical weights in page metadata

---

source/optional_features/digital_wallets/index.html.md.erb

GOV.UK Pay fully decrypts the apple pay payload before passing to worldpay, so
there's no need to enable any special settings in worldpay.
We had a question about this from a partner service who wanted confirmation as
to whether this setting was needed. It's mentioned in Worldpay's docs:
https://beta.developer.worldpay.com/docs/wpg/mobilewallets/applepay#setup
Explicitly state that worldpay config changes not needed
Possibly we don't need to explain why here. I would be ok with that :-). I used the same language to describe this setting as is used in Worldpay's docs.

Clarify apple pay doesn't need Worldpay setting

---

source/integrate_with_govuk_pay/index.html.md.erb

If teams search payments at (say) midnight at the end of each day, and use an end time of midnight, they may miss some payments - because the API may not return fully up-to-date information about payment events from the last hour.
Add docs to our section about [integrating finance and accounting systems](https://docs.payments.service.gov.uk/integrate_with_govuk_pay/#finance-and-accounting-systems) on using an end date at least one hour before your search time, so you make sure to get up-to-date information about payment events up to that time.

Add docs about when to search payments

---

source/account_structure/index.html.md.erb
source/api_reference/index.html.md.erb
source/direct_debit/index.html.md.erb
source/integrate_with_govuk_pay/index.html.md.erb
source/optional_features/custom_branding/index.html.md.erb
source/optional_features/delayed_capture/index.html.md.erb
source/optional_features/use_your_own_error_pages/index.html.md.erb
source/payment_flow/index.html.md.erb
source/quick_start_guide/index.html.md.erb
source/reporting/index.html.md.erb

Bullet lists are inconsistent across the tech docs. Some of the lists use single line spacing while others use double line spacing (such as [Quick start](https://docs.payments.service.gov.uk/quick_start_guide/#quick-start-guide)).
Make all bullet lists use single line spacing, so they're consistent with GOV.UK style and other GDS tech docs. 
Please check it all looks ok.

Fix bullet spacing

---

source/payment_flow/index.html.md.erb
source/reporting/index.html.md.erb

Teams should not use the [search payments](https://docs.payments.service.gov.uk/reporting/#generate-a-list-of-payments-search-payments) API call during payment flow to check the status of a payment, because search is asynchronous so the payment status returned may not be up-to-date. 
Add docs to:
- Payment flow
- Reporting
We do not have documentation about the 'Get events for a payment' API call. To keep this an agile change, I've linked to the API browser for now, and I'll add documentation about that call to the tech docs later.

Add docs about search being asynchronous

---

source/optional_features/custom_metadata/index.html.md.erb

Teams can now add metadata ('reporting columns') to payment links.
Update the [custom metadata](https://docs.payments.service.gov.uk//optional_features/custom_metadata/#add-metadata-to-a-payment) page to direct payment link users to the admin tool.

Add link to adding payment links metadata

---

source/direct_debit/index.html.md.erb

Minor changes to the Direct Debit page to clarify that Direct Debit functionality is not currently available to central government departments in England or the NHS.

Clarify Direct Debit availability

---

source/account_structure/index.html.md.erb
source/api_reference/index.html.md.erb
source/payment_flow/index.html.md.erb

Alt tags for decorative images (where the content is already explained in surrounding text, so `alt` text is not needed) are rendering as `alt="``”``"`. This will be potentially confusing for users who use screen readers. 
Fix the markdown for each image so the HTML renders as just `alt`, in line with other documentation examples. This passes the accessibility check at for example https://wave.webaim.org/.

Fix empty alt tags

---

source/account_structure/index.html.md.erb
source/api_reference/index.html.md.erb
source/payment_flow/index.html.md.erb

Reverts alphagov/pay-tech-docs#426 because the build failed - htmlproofer does not like the empty alt tags.

Revert "Fix empty alt tags"

---

config.rb
source/account_structure/index.html.md.erb
source/api_reference/index.html.md.erb
source/payment_flow/index.html.md.erb

Alt tags for decorative images (where the content is already explained in surrounding text, so alt text is not needed) are rendering as alt="``”``". This will be potentially confusing for users who use screen readers.
Fix the markdown for each image so the HTML renders as just alt, in line with other documentation examples. This passes the accessibility check at for example https://wave.webaim.org/.
This also involves updating `htmlproofer` config so it ignores empty alt tags, otherwise the build will fail (as happened with https://github.com/alphagov/pay-tech-docs/pull/426).

Fix empty alt tags and update htmlproofer config

---

source/making_payments/index.html.md.erb

We need to clarify that:
- the minimum payment includes the PSP transaction fee
- the maximum payment is different if you use the Government Banking Service
Update the [Making payments](https://docs.payments.service.gov.uk/making_payments/#making-payments) page with the extra content about minimum and maximum payments.

Clarify maximum and minimum payments

---

config/tech-docs.yml

Daniel the Manual Spaniel is using incorrect urls for his Slack alerts, because the host url for the Pay tech docs is set wrongly in `tech-docs.yml`.
Fix the host url (the lack of trailing slash is important).
Please check it looks ok

Fix host url in config file

---

source/integrate_with_govuk_pay/index.html.md.erb

We're adding payout reporting for Stripe to the GOV.UK Pay admin tool.
Add a link in the [finance and accounting section of the integrating docs](https://docs.payments.service.gov.uk/integrate_with_govuk_pay/#finance-and-accounting-systems).
Do not merge until the payout reporting is live.

Add link to Stripe payout reporting

---

source/switching_to_live/set_up_a_live_stripe_account/index.html.md.erb

There's a new page we can link to with guidance on being someone authorised to sign contracts on behalf of your organisation (a 'responsible person').
Add a link to the guidance from our Stripe 'go live' documentation.

PP-6665 Add link to responsible person guidance

---

source/optional_features/moto_payments/index.html.md.erb

We need to clarify that if teams want to use MOTO payments and they're using Worldpay and ePDQ as their PSP, they need to create a separate GOV.UK Pay service and get a separate merchant code.
Add the clarifications above.

Clarify MOTO payments

---

source/account_structure/index.html.md.erb
source/index.html.md.erb
source/integrate_with_govuk_pay/index.html.md.erb
source/making_payments/index.html.md.erb
source/payment_flow/index.html.md.erb
source/set_up_3dsecure/index.html.md.erb
source/switching_to_live/index.html.md.erb
source/switching_to_live/set_up_a_live_epdq_account/index.html.md.erb
source/switching_to_live/set_up_a_live_smartpay_account/index.html.md.erb
source/switching_to_live/set_up_a_live_stripe_account/index.html.md.erb
source/switching_to_live/set_up_a_live_worldpay_account/index.html.md.erb

You must have a contract with a Payment Service Provider (PSP) to process the payments taken using GOV.UK Pay. 
You can use either of the following PSPs with GOV.UK Pay:
- GOV.UK Pay's PSP, Stripe
- if you are a central government or health sector organisation, Government Banking's PSP, WorldPay
You cannot use GOV.UK Pay with any other PSPs.
The tech docs must be amended to reflect that you cannot BYO contract with a non Stripe or non Worldpay PSP to GOV.UK Pay.
Clarify that you must use either the Stripe or Worldpay PSPs with GOV.UK Pay
Check that it accurately reflects reality and that nothing is missing.

Remove references to BYO Contract

---

source/switching_to_live/index.html.md.erb
source/switching_to_live/set_up_a_live_epdq_account/index.html.md.erb
source/switching_to_live/set_up_a_live_smartpay_account/index.html.md.erb
source/switching_to_live/set_up_a_live_stripe_account/index.html.md.erb
source/switching_to_live/set_up_a_live_worldpay_account/index.html.md.erb

Need to clarify that you cannot move an existing direct Worldpay contract over to Government Banking.
- Clarify that you cannot move an existing direct Worldpay contract over to Government Banking
- Split out Stripe / Govt Banking vs others
Check if accurate

Clarify moving Worldpay contracts (BYOC redux) 

---

source/quick_start_guide/index.html.md.erb

The fact check a thon checked the accuracy of the different tech docs pages.
Clarify the following:
- 'when you've received a test account' means when you have signed up to a test account or joined the service.
- "Do not use an API key from a live account on the GOV.UK Pay admin tool. Only use a test API key." means "Do not use an API from a live account to test Pay."
- you can view test transactions in the API

Fact check a thon - Quick Start Guide

---

source/integrate_with_govuk_pay/index.html.md.erb

Nick F, Rebecca C and I reviewed some tech docs research that Nick and Mark Green carried out in March and April.
One of the things being tested in the docs was the diagram that "shows a typical high-level architecture with a GOV.UK Pay integration" located in https://docs.payments.service.gov.uk/integrate_with_govuk_pay/#integrate-with-the-gov-uk-pay-api. 
The feedback on this diagram was neutral, with some people stating it was helpful and some stating it was confusing (simplifying massively here but you get the idea). 
We checked with @alexbishop1 and @sfount and agreed to remove this diagram.
Remove first diagram in https://docs.payments.service.gov.uk/integrate_with_govuk_pay/#integrate-with-the-gov-uk-pay-api.

Remove inaccessible and confusing diagram

---

config/tech-docs.yml
source/accessibility.html.md.erb

The deadline for publishing an accessibility statement is 23 September 2020. The GOV.UK Pay product pages already have a statement published. The content of the tech docs need an accessibility statement as well. This is separate to the statement on the tech doc template itself, which is being handled as part of a separate project.
Add an accessibility statement for tech docs.

Add an accessibility statement for tech docs

---

source/custom_metadata/index.html.md.erb

For payment metadata, we now support string values of up to 100 characters (previous was 50).

PP-7067 Update maximum metadata string value length from 50 to 100

---

config/tech-docs.yml

In order to see search queries for the tech docs, we needed to verify that we had ownership of the domain.
This pull request adds a new verification code that allows us to gain access to Search Console data for the tech docs and add accounts for other members of the team.

Add new site verification code

---

source/custom_metadata/index.html.md.erb
source/integrate_with_govuk_pay/index.html.md.erb
source/payment_flow/index.html.md.erb
source/reporting/index.html.md.erb

My service should be My services 
consider /v1/payments/{paymentId} to indicate variable more clearly (and likewise throughout) 
In text we note two things you may want to do (get a single payment, search for multiple payments), but we have sections corresponding to 3 things (<- + get payment events) 
https://docs.payments.service.gov.uk/reporting/#checking-when-your-payment-service-provider-psp-took-a-payment is a bit unclear. We store captured date for PSPs other than worldpay (stripe), and it may not always be the case that settlement will occur 2 days after capture in those cases. Might need a rethink, and also how this re4lates to payout reporting. 
The sentence 'Search results are asynchronous so the payment status may not be up-to-date.' isn't quite right. The search results aren't …

Fact check a thon - reporting

---

source/set_up_3dsecure/index.html.md.erb

Corrects UK only date to September 2021

Fix UK date to 2021

---

source/optional_features/custom_branding/index.html.md.erb

The docs currently suggest custom branding logos can only go on the left of the header, which is incorrect
Added the ability to put the logo on the right-hand side for custom branding

Logos can go on the right

---

.gitignore
.secrets.baseline
README.md
ci/pipeline.yml
config.rb
config/tech-docs.yml
package-lock.json
package.json
source/javascripts/analytics.js
source/javascripts/application.js
source/javascripts/application.test.js
source/stylesheets/screen.css.scss

Include all distribution code from the pay js commons analytics folder
IFF it exists (has been npm installed).
* Importantly the build process
should pass without the files being there, allow testing the main app
functionality locally without analytics;
*  the production instance will then ensure `npm install` has been
correctly run and include the analytics client side JavaScript.
* optionally include sass required for banner
* The tech docs gem only includes part of `govuk-frontend` that it needs.
* The analytics consent banner require button styles. Unless this code
becomes part of the core tech docs gem, it will need the ability to
include these additional styles. Add an import for the button style with
a guard against dev not having included npm dependencies locally.
* Hook show …

PP-6284: optionally include js commons analytics

---

source/api_reference/index.html.md.erb
source/payment_flow/index.html.md.erb

As part of the 2020 accessibility work, we should remove the following two diagrams from the tech docs as they are not accessible (use colour to denote meaning, not an svg format, alt text, not clear, not necessary):
- https://docs.payments.service.gov.uk/api_reference/#payment-status-lifecycle
- https://docs.payments.service.gov.uk/payment_flow/#overview
The payment flow overview diagram is already described in the body text so does not need any further changes.
The payment status lifecycle diagram needs to be described in the body text so this ticket will encompass that work.

Remove inaccessible diagrams

---

source/account_structure/index.html.md.erb
source/api_reference/index.html.md.erb
source/corporate_card_surcharges/index.html.md.erb
source/direct_debit/index.html.md.erb
source/integrate_with_govuk_pay/index.html.md.erb
source/switching_to_live/index.html.md.erb
source/switching_to_live/set_up_a_live_epdq_account/index.html.md.erb
source/switching_to_live/set_up_a_live_smartpay_account/index.html.md.erb

Fixes as part of accessibility corrections after the audit to remove redundant links and alt text:
https://wave.webaim.org/report#/https://docs.payments.service.gov.uk/account_structure/#how-accounts-work - shorten or remove alt text
https://wave.webaim.org/report#/https://docs.payments.service.gov.uk/direct_debit/#take-a-direct-debit-payment - remove “redundant” links i.e. concurrent identical links
https://wave.webaim.org/report#/https://docs.payments.service.gov.uk/corporate_card_surcharges/#add-corporate-card-fees - remove “redundant” links i.e. concurrent identical links
https://wave.webaim.org/report#/https://docs.payments.service.gov.uk/integrate_with_govuk_pay/#integrate-with-the-gov-uk-pay-api - remove “redundant” links i.e. concurrent identical links …

A11y fixes - Remove redundant links and alt text

---

source/set_up_3dsecure/index.html.md.erb

Services now need to press a button to enable 3DS Flex after they’ve entered their 3DS Flex credentials. They’ll be on the page with the button after they’ve entered the credentials and the button will not appear if the credentials have not been entered.
Add ‘Select **Turn on 3DS Flex**’ to list of instructions.

PP-7416 Add ‘Select Turn on 3DS Flex’ to 3DS Flex instructions

---

source/set_up_3dsecure/index.html.md.erb

Although we did work earlier in the year to support 3DS2 for ePDQ, it wasn’t available for live ePDQ accounts at the time. It seems to now be available but we haven’t yet configured any accounts to use it.
See changes in pull request.
Text is basically the same as what we say for Smartpay.

We don’t yet have 3DS2 enabled for ePDQ

---

source/accessibility.html.md.erb

Updated the date for fixing the Tech Docs Template accessibility issues from “end of December 2020” to “end of March 2021”. As a result of resourcing pressures and re-prioritisation this year, it’s taking longer than we hoped to arrange developer and designer resources to fix the accessibility issues.

Update accessibility statement dates

---

ci/pipeline.yml

Description:
- Deploy and builds are failing on Concourse because it is pulling the latest Ruby version. This PR ensures that it pulls a specific version of the Ruby docker image rather than the latest one.

BAU - Fix Ruby version error

---

source/quick_start_guide/index.html.md.erb

Forgot to update the last date reviewed for the quick start guide in September 2020

Quick start guide review date change

---

source/reporting/index.html.md.erb

Fact check suggestion that we add a direct link to view all service transactions in the [manual reporting](https://docs.payments.service.gov.uk/reporting/#manual-reporting) docs. 
Change the UI step to a direct link.

PP-7617 Update step in manual reporting to direct admin link

---

source/api_reference/index.html.md.erb

A fact check raised the issue that in https://docs.payments.service.gov.uk/api_reference/#use-the-api, we don't mention how to get a payment's information through the API.
Added a link to the page about making a request to the API to get a payment's information.

PP-7616 Add link to getting payment using API in errors section

---

source/payment_flow/index.html.md.erb

Issues raised in fact check of payment flow page:
- `self` and `next_url` aren't clear that the URL is in the `href` field, not the parent object
- the unique identifier is at the end of the URL, not the whole URL
- it's not clear you need to make an API request to `self` to get the payment details
Clarify the content to fix the issues above

PP-7613 Clarify self and next_url in payment flow

---

source/optional_features/welsh_language/index.html.md.erb
source/payment_flow/index.html.md.erb
source/refunding_payments/index.html.md.erb
source/reporting/index.html.md.erb
source/security/index.html.md.erb
source/switching_to_live/index.html.md.erb
source/testing_govuk_pay/index.html.md.erb

Some of the URLs in the admin tool are being changed.
Update links to certain admin tool pages with content about first selecting the account you need, then going to the appropriate area of the admin tool.
I haven't described every step because it would make the user experience more complicated than necessary. I've written the content to take users far enough that the remaining steps should be self-explanatory through the admin tool UI design.
Do not merge until all the urls have been changed in the admin tool itself. (Redirects should mean user journeys continue to work in the meantime.)

PP-7634 Update content to reflect new admin tool URLs

---

source/switching_to_live/index.html.md.erb

We're missing content for users to tell them that you cannot use your own Worldpay contract after 31 July 2021.
Add the content to the relevant [Go live section](https://docs.payments.service.gov.uk/switching_to_live/#2-connect-your-live-account-to-your-psp) and reorder the content so the options are clearer. 

PP-7528 Add deadline for teams' own Worldpay accounts

---

source/api_reference/index.html.md.erb
source/block_prepaid_cards/index.html.md.erb
source/corporate_card_surcharges/index.html.md.erb
source/delayed_capture/index.html.md.erb
source/direct_debit/index.html.md.erb
source/index.html.md.erb
source/making_payments/index.html.md.erb
source/moto_payments/index.html.md.erb
source/optional_features/custom_branding/index.html.md.erb
source/optional_features/use_your_own_error_pages/index.html.md.erb
source/optional_features/welsh_language/index.html.md.erb
source/security/index.html.md.erb
source/support_contact_and_more_information/index.html.md.erb
source/switching_to_live/index.html.md.erb

A fact check on the Support page highlighted some areas for clarification.
I've borrowed content from the [product support page](https://www.payments.service.gov.uk/support/) to make it clearer how to contact us in an emergency.
I've also taken the opportunity to:
- restructure the page with fewer headings so it's easier to understand (this is especially important given that this page will be used in emergencies), and closer to the product support page
- make the P1 (critical) description match the product support page, to avoid confusion through inconsistency
- fix ambiguities and style issues across the page as a whole
- make improvements to the incident table - the style is now closer to the GOV.UK style already used by the GDS Way incident table
I haven't added clarification that the …

PP-6479 Clarify support page and make it more consistent with product support page

---

source/direct_debit/index.html.md.erb

Reverts alphagov/pay-tech-docs#542 because of a failed build.

Revert "PP-7721 Replace Direct Debit content with research contact"

---

source/direct_debit/index.html.md.erb

The build for https://github.com/alphagov/pay-tech-docs/pull/542 failed because of an error resolving a merge conflict. We reverted that PR, and now this PR redoes the content changes.

Redo content changes from PR 542

---

source/security/index.html.md.erb

Users are able to make 'risk management' fraud checks if their PSP is Smartpay.
Add Smartpay to the docs on [preventing fraudulent payments through risk management](https://docs.payments.service.gov.uk/security/#preventing-fraudulent-payments).
Do not merge until PP-7672 technical change has been made.

PP-7672 Add sending IP address to SmartPay

---

source/api_reference/index.html.md.erb
source/quick_start_guide/index.html.md.erb
source/refunding_payments/index.html.md.erb
source/reporting/index.html.md.erb
source/switching_to_live/index.html.md.erb
source/testing_govuk_pay/index.html.md.erb

Users can request test Stripe accounts to see:
- transaction fees
- payments to your bank account
- Update references to 'test' accounts if we mean specifically a sandbox or a Stripe test account
- Add a journey to request a test Stripe account on appropriate pages 
- Add mock card numbers for Stripe test accounts

PP-7675 Fix urls and add journey to requesting Stripe test account

---

Gemfile.lock
source/account_structure/index.html.md.erb
source/account_structure/set_up_where_payments_go/index.html.md.erb
source/account_structure/set_up_where_services_link_to/index.html.md.erb
source/integrate_with_govuk_pay/index.html.md.erb
source/making_payments/index.html.md.erb

We've received requests from users who are confused about or need more help setting up multiple accounts.
This improves the [How accounts work](https://docs.payments.service.gov.uk/account_structure/#how-accounts-work) tech docs page to better meet user needs.
I’ve aimed to:
- lead with the need for each type of setup, so users can more easily pick the approach that matches what they’re trying/need to do
- use language like “send your users…” and “send payments…” to make it easier to understand the flow of payments through accounts
- make the content more task-based (so it uses headings like ‘Decide where to…’ and now includes how to actually set up accounts in the different ways)
We’re a bit stuck with how the admin tool uses “accounts” and “services” to mean different things, but I’ve …

PP-6802 Improve accounts page

---

source/account_structure/set_up_where_services_link_to/index.html.md.erb
source/api_reference/index.html.md.erb
source/digital_wallets/index.html.md.erb
source/integrate_with_govuk_pay/index.html.md.erb
source/moto_payments/index.html.md.erb
source/optional_features/welsh_language/index.html.md.erb
source/quick_start_guide/index.html.md.erb
source/reporting/index.html.md.erb
source/switching_to_live/index.html.md.erb

When users go to https://selfservice.payments.service.gov.uk/, they'll be taken to the My Services page (https://selfservice.payments.service.gov.uk/my-services) rather than an individual account dashboard.
Update guidance on navigating from https://selfservice.payments.service.gov.uk/, so it matches the new journey.
As with https://github.com/alphagov/pay-tech-docs/pull/536, I haven't described every step because it would make the user experience more complicated than necessary. I've written the content to take users far enough (for example to the Settings page) that the remaining steps should be self-explanatory through the admin tool UI design 
Do not merge until the admin tool has been changed.

PP-7674 Update user journeys to reflect new admin page default

---

source/testing_govuk_pay/index.html.md.erb

Our [table of payment cards for Stripe test accounts](https://docs.payments.service.gov.uk/testing_govuk_pay/#if-you-39-re-using-a-test-stripe-account) is missing non-US cards. 
Add non-US cards to the table, and guidance on the transaction fee varying depending on country.

PP-7866 Add non-US Stripe test cards

---

source/switching_to_live/index.html.md.erb

Some users aren't sure which service to request a live account from.
Clarify that you can go live from both types of test account.

PP-7852 Clarify you can go live from both types of test account

---

source/api_reference/index.html.md.erb
source/custom_metadata/index.html.md.erb
source/delayed_capture/index.html.md.erb
source/integrate_with_govuk_pay/index.html.md.erb
source/making_payments/index.html.md.erb
source/optional_features/prefill_user_details/index.html.md.erb
source/optional_features/use_your_own_error_pages/index.html.md.erb
source/quick_start_guide/index.html.md.erb
source/refunding_payments/index.html.md.erb
source/reporting/index.html.md.erb
source/versioning/index.html.md.erb

Our API browser has accessibility issues, so we're moving relevant content into our public tech docs (and redirecting the API browser to tech docs).
I've moved as many API browser examples, parameters and descriptions into the tech docs content as I can.
A few things worth bearing in mind:
- I've removed or restructured some content where it overlapped or duplicated the content I've brought over from the API browser (most notably on the API reference page)
- In the interests of avoiding duplication and overlong pages, I've sometimes left out fields from API responses where they're implied or obvious - for example in the 'Get information a payment' API response example, I mostly haven't included the fields that users supplied themselves as parameters in their original 'make a payment' …

PP-7883 Move API browser content into tech docs

---

source/api_reference/index.html.md.erb
source/contribute/index.html.md.erb
source/support_contact_and_more_information/index.html.md.erb

**Do not merge until repo has been updated to govuk_tech_docs v2.2.0+**
The updated Tech Docs Template gem adds the [govspeak feature that lets you add row heading markup to tables](https://www.gov.uk/guidance/content-design/tables#use-headers).
Make relevant tables accessible by adding row heading markup.
I've excluded tables where:
- there are only 2 columns
- the first column does not have row headings
Please check affected tables have row heading markup in generated HTML.

Add table row header markup

---

config/tech-docs.yml

The 'About' link in the header is causing an accessibility issue, because (despite the #about anchor), it goes to the same page as the GOV.UK logo.
Remove the 'About' link
Please check it looks ok.

Remove redundant header link

---

source/switching_to_live/index.html.md.erb

When requesting a Live account for Pay, users need to provide details of their organisation, tell us which Payment Service Provider they'll be using, and agree to our terms and conditions. Currently the 'Go live' page in the Pay docs only lists the first two steps. This change adds the third step (agreeing to terms and conditions).

PP-7744 - Adds information about agreeing to Pay's terms and conditions on the 'Go Live' page

---

source/reporting/index.html.md.erb

Description of `metadata` object was missing from the 'Report on a payment' page.
Adds a description of the `metadata` object to the reporting page of the Pay docs, as well as a suggested use case - reconciliation.

Adds metadata description to Reporting docs

---

package-lock.json
package.json

- Old version of 'pay-js-commons' used the wrong version number of 3.1.0.
- Update the pay-js-commons to the latest version with the correct version number
3.0.12

PP-8015 Fix and update the version of pay-js-commons used.

---

source/versioning/index.html.md.erb

There have been [several enquiries](https://payments-platform.atlassian.net/browse/PP-7591) about whether we follow the API standards and how likely it is that GOV.UK Pay integrations could break when we update the API. 
This PR adds a link to the section of the API standard around iteration. It also updates some outdated wording left over from when the Pay API was in beta.
My questions are:
- Is just linking to the 'Iteration' section of the standards enough?
- Do we need to provide any more information around what adherence to the API standards entails?

PP-7591 - Adds a link to API standards iteration guidance

---

source/quick_start_guide/index.html.md.erb

The Quick Start featured guidance on how to get an API key but not what to do with it.
This PR adds a link to the Authentication section of the API reference that explains how the API key should be used.

PP-8113 - Adds a link to authentication guidance to the Quick Start guide

---

source/api_reference/index.html.md.erb
source/delayed_capture/index.html.md.erb
source/making_payments/index.html.md.erb
source/refunding_payments/index.html.md.erb
source/reporting/index.html.md.erb

Previously, there were 5 different formats for parameter placeholders in the Pay tech docs. This PR standardises the formatting of these.
- Standardises API parameter placeholders to `{CAPITAL_LETTERS}` format.
- Adds additional clarification after placeholders with 'Replace `{PLACEHOLDER_NAME}` with...' sentences.
- Do the clarification sentences ('Replace `{PLACEHOLDER_NAME}` with...') read okay? The wording on some of them was tricky.
- Do the examples still make sense? Especially the query parameters placeholder in _Refund a payment_ -> _Searching refunds_ 
- Have I broken anything?

PP-6741 - Standardises formatting of all API parameter placeholders

---

source/api_reference/index.html.md.erb

I changed the name of a heading and forgot to fix an anchor link on another page.
Fixed the anchor link on the API reference page.

Fixed anchor link from API reference page

---

source/making_payments/index.html.md.erb
source/refunding_payments/index.html.md.erb
source/reporting/index.html.md.erb

In a previous Pay tech docs fact check, Steven F. pointed out that ISO 8601 has different levels of precision when specifying times and dates. We currently do not outline the level of precision that the Pay API requires.
This PR explains the level of date and time precision required for the `from_date`, `to_date`, `from_settled_date`, and `to_settled_date` query parameters require. It also changes the formatting of an example API call to match other call examples in the documentation.
For pre-i:
- I'm not sure if I describe the level of accuracy required as well as I could in line 294

Clarifies date formatting for refund dates and settled dates.

---

source/making_payments/index.html.md.erb
source/reporting/index.html.md.erb

These fixes were flagged by devs back in May.
- Removed an internal link from the Reporting page.
- Updated `paymentId` API parameters to `payment_id` to better reflect how it appears in responses.

Remove internal link and fix formatting on API params.

---

source/switch_payment_service_provider/index.html.md.erb
source/switch_payment_service_provider/switch_psp_to_stripe/index.html.md.erb
source/switch_payment_service_provider/switch_psp_to_worldpay/index.html.md.erb

Services can no switch their payment service provider (PSP) to Worldpay or Stripe.
Added a new section and 3 new pages to the documentation. A top-level page with information about switching in general, then a page of guidance each for Stripe and Worldpay.

PP-8220 - Switching PSP guidance

---

source/switching_to_live/index.html.md.erb

The BYOC deadline has changed from 31 July 2021 to 31 December 2021. 
- Updates the dates for the BYOC deadline
- Normalises the formatting of the dates

Updated BYOC dates in Go Live docs

---

source/moto_payments/index.html.md.erb

Telephone payment links have been in private beta for a while. As they move into public beta, we need something in the documentation to explain them.
This PR:
- restructures the existing telephone payments page into 'Set up MOTO payments' and 'Take a MOTO payment'
- adds guidance around setting up telephone payment links and using telephone payment links to take payments
- improves existing guidance on setting up and creating MOTO payments through the API
- makes new and existing email links more accessible
This content has already been reviewed by Alex Bishop (telephone payment links dev) and been through the tech writer 2i process.

PP-8398 - Updated MOTO page to include telephone payment link guidance

---

source/quick_start_guide/index.html.md.erb

Pay should be referred to as 'GOV.UK Pay'.
Change one reference of 'Pay' to 'GOV.UK Pay'

Corrected an inconsistent reference to Pay

---

source/switch_payment_service_provider/switch_psp_to_stripe/index.html.md.erb
source/switch_payment_service_provider/switch_psp_to_worldpay/index.html.md.erb

The switching PSP guidance had the following issues:
* Formatting was incorrect for both Stripe and Worldpay UI text.
* Stripe guidance referred to a Worldpay link
Corrects formatting and wording errors.

Minor fixes to Stripe and Worldpay switching guidance

---

source/making_payments/index.html.md.erb

As [highlighted by Jon in a JIRA ticket](https://payments-platform.atlassian.net/browse/PP-6747?atlOrigin=eyJpIjoiMmM1NDY0YzA0MmFiNDE0ZjkxYjQxMWExYjhiYTVmNTQiLCJwIjoiaiJ9), the [current documentation](https://docs.payments.service.gov.uk/making_payments/#receiving-the-api-response) doesn't make it obvious what the differences are between the URLs in the `self` section and `next_url` section of the API response after creating a new payment.
For context, the `self` URL is a unique URL for the payment that API users can use to get information about the payment. The `next_url` URL is where paying users will go to make their payment.
Clarify the differences between `self` and `next_url`.
* Is 'section' the right wording here?
* Does this make the differences between the two URLs clear?
* Can …

Updated 'Taking a payment' to make 'self' and 'next_url' differences more obvious.

---

source/delayed_capture/index.html.md.erb
source/digital_wallets/index.html.md.erb
source/making_payments/index.html.md.erb
source/moto_payments/index.html.md.erb
source/reporting/index.html.md.erb
source/set_up_3dsecure/index.html.md.erb
source/switch_payment_service_provider/switch_psp_to_worldpay/index.html.md.erb
source/switching_to_live/index.html.md.erb
source/switching_to_live/set_up_a_live_epdq_account/index.html.md.erb

These are minor fixes to issues that were found in the GOV.UK Pay tech docs in August 2021
This PR fixes:
- Payment service provider (PSP) capitalisation
- PSP initialism frequency - should only appear once in the first instance
- Changes references to 'My Services' to 'Overview'
- Fixed a reference to 'Find payment by ID'

PP-8516 - Minor docs changes [August 2021]

---

source/switch_payment_service_provider/index.html.md.erb

FCDO were unsure about whether payment links would be affected by switching PSP. This PR clarifies the behaviour under the 'What the switch affects' heading.

Clarified payment link functionality after switching PSP.

---

source/reporting/index.html.md.erb
source/set_up_3dsecure/index.html.md.erb

It is now possible to view 3D Secure authentication details about a payment through the Pay Reporting API.
This PR makes the following changes:
- Adds `authorisation_summary` object to the API response example on the 'Report on a payment' page
- Adds definitions of `authorisation_summary`, including `required` and `version` objects
- Adds a link to the 'Report on a payment' page to the 'Set up SCA' page
- Is the `authorisation_summary` definition accurate?
- Has `authorisation_summary` been added to the correct part of the response example?
- Do the `version` values (`2.2.0`, `2.1.0`, `1.0.2`) need their own definitions?
- I switch between 'authorisation' and 'authentication' a bit. 'Authorise' is how Pay refer to it, but 'authenticate' is how 3DS is referred to elsewhere. Is this …

PP-8614 - Documentation for 3DS details in Reporting API

---

source/javascripts/analytics.js

- Fix bug with the domain not getting set correctly on the
Google Analytics GA cookie.
- Explicitly set the domain when running `ga('create', ...)`

PP-8519 Google Analytics - set domain on Google cookie

---

source/switch_payment_service_provider/switch_psp_to_stripe/index.html.md.erb

Updated URL for 
GOV.UK Pay contract (if you are a non-Crown organisation)
Memorandum of Understanding (if you are a Crown organisation)
Stripe Connected Account Agreement.
A user pointed out some broken links on our PSP switching page. 
Change the links of the Pay contracts from old to new 
You must be logged in to view the links

Fix broken links to Pay contract

---

source/switch_payment_service_provider/switch_psp_to_stripe/index.html.md.erb
source/switching_to_live/set_up_a_live_stripe_account/index.html.md.erb

[PP-8962](https://payments-platform.atlassian.net/browse/PP-8962#icft=PP-8962) adds a document uploader to allow services to prove that they are government entities. Services that use GOV.UK Pay and choose Stripe as their service provider must upload a document that proves they are a government entity. Only certain documents are allowed.
This PR makes changes to the following pages:
- Connect your live account to Stripe
- Specifies the valid documents for proving government entity status
- Switch payment service provider to Stripe
- Specifies the valid documents for proving government entity status
- Adds a document upload step to the process for switching to Stripe
Notes:
* the UI text in line 102 of switch_psp_to_stripe is TBC - content designer needs to review it. Will update that text …

Adds proving government entity status details + document upload steps

---

source/switch_payment_service_provider/switch_psp_to_stripe/index.html.md.erb

When services request to switch PSP to Stripe, we currently ask for their payment descriptor through Zendesk. This is wasteful when they could include it in their initial switch request.
This PR adds a few lines to the start of the 'Switching PSP to Stripe' guidance. The new content asks services to send us payment descriptors for each service they're switching over to try and avoid having to ask this via Zendesk email later in the process.
It links out to Stripe's guidance on good descriptors to avoid copying the information ourselves.

Adds a request for payment descriptors to initial switch PSP email

---

Gemfile
Gemfile.lock

This gem is now brought in by the govuk_tech_docs gem (see Gemfile). The previous dependency was fetching from git in a deprecated manner and [causing a failure in the PR build process](https://pay-cd.deploy.payments.service.gov.uk/teams/pay-dev/pipelines/pay-tech-docs/jobs/build-pr/builds/21.1).
Tested the search functionality locally without the dependency as a separate gem.

BAU: Remove explicit dependency on middleman-search

---

source/testing_govuk_pay/index.html.md.erb

New Stripe fees are being introduced in January 2022. From April 2022, Pay services will be responsible for these fees. There is not currently a way to test 3DS fees using test cards in our documentation.
Adds a new Stripe test card that guarantees a 3DS check so that services can test their integrations with the new fees.

Adds new Stripe test card

---

source/integrate_with_govuk_pay/index.html.md.erb
source/reporting/index.html.md.erb

PP-8951 implements Stripe's new fee structure, including the possibility of fees on failed payments and changes to the behaviour of the `total_amount` and `net_amount` values.
This PR changes the following page s:
- Report on a payment
- `net_amount` - updated description to mention negative amounts
- `total_amount` - updated description to make it clear that it only appears when there is a corporate card surcharge
- Added links to 'Integrate with GOV.UK Pay API', which explains how negative `net_amount` can occur
- Integrate with GOV.UK Pay API
- Updated 'Checking when your PSP sent a payment' to include the possibility of payments being taken from Stripe balance if they fail but have fees

PP-9088 - Documentation for failed transaction fees

---

source/making_payments/index.html.md.erb

Make the domains in the URLs match reality.

BAU — Correct next_url and next_url_post examples

---

source/switching_to_live/index.html.md.erb

We occasionally get service desk enquiries where a service admin has made a £1 test payment and, after transaction fees are taken, they are unable to get this test payment back as they are short of the £1 minimum payout threshold.
This PR updates the Go Live documentation to recommend that test payments are at least £2 to ensure that they can make a payout to test their integration. This is in line with our advice during the PSP switching process.

Updated Go Live test payment amount advice.

---

source/making_payments/index.html.md.erb

Some services have been trying to use the search payments API call to check the status of payments after users reach the return_url. This was providing inaccurate status information.
Improve the description of what services should do when their users are directed to their return_url.

Clarified which calls services should and should not use.

---

source/switch_payment_service_provider/switch_psp_to_stripe/index.html.md.erb

- Service cannot take a test payment until Stripe has confirmed their details. Next step button is not visible if the process is still ongoing.

PP-9155 update verify your PSP docs - take a test payment

---

nginx.conf

`pay-tech-docs.cloudapps.digital` was found running in the `govuk-service-manual` organisation and is being deleted.
Just removing this reference in case anyone gets confused by it in the future

pay-tech-docs.cloudapps.digital has been deleted

---

source/moto_payments/index.html.md.erb

Make it `"moto": true` rather than `“moto”: true`.

BAU — MOTO: Replace curly quotation marks with straight ones

---

source/api_reference/index.html.md.erb

The table of endpoints in the API reference look odd because of inconsistent line breaks in the 'Data consistency' column.
This PR adds `<nobr` tags to the data consistency column to prevent inconsistency.

Added <nobr> tags to fix inconsistent tables

---

source/api_reference/index.html.md.erb

To prevent wrapping issues with table entries, we've previously manually created HTML tables in the tech docs. HTML tables are trickier to edit and stick out because the rest of the docs are entirely in Markdown. 
This PR changes the last HTML table to markdown and uses <nobr> tags to prevent wrapping. The content is identical.

Uses markdown with <nobr> tags, rather than pure HTML, to make a table.

---

source/api_reference/cancel_payment_reference/index.html.md.erb
source/api_reference/create_a_payment_reference/index.html.md.erb
source/api_reference/single_payment_reference/index.html.md.erb
source/corporate_card_surcharges/index.html.md.erb
source/optional_features/custom_branding/index.html.md.erb
source/switch_payment_service_provider/switch_psp_to_worldpay/index.html.md.erb
source/switching_to_live/index.html.md.erb

Minor documentation fixes are bundled together into a single PR.
This PR:
- Makes it clearer how users need to get to PSP-specific guidance in the Go live docs
- Improves the custom branding banner logo instructions
- Changes ‘prepaid credit and debit cards’ to ‘prepaid debit cards’
- Adds a step to Switch to Worldpay guidance to enable 3DS Flex after switching
- Adds `GET` to the example request in the Get single payment API reference page
- Add an introductory sentence before the example request in the Create a payment API reference page
- Add backticks to `204` HTTP code in the response section of the Cancel a payment API reference page

PP9897 - Minor docs changes for July 2022

---

source/send_card_details_api/index.html.md.erb

This PR fixes the wording on the authorisation API page to be more consistent with the rest of the docs.

Changes auth API page to be more readable

---

source/prefill_payment_links/index.html.md.erb

Users can now add `amount` and `reference` query parameters to a payment link. This prefills the payment amount and payment reference fields when the user opens the link.
Typically we haven't documented payment link features as payment links as the 'non-technical' way to take payments. However, given that this feature currently requires manually editing of the URL, we think it's technical enough for a docs page.
This PR adds a new page to the Pay documentation explaining this functionality.

Adds guidance to prefill payment link details 

---

source/delayed_capture/index.html.md.erb
source/making_payments/index.html.md.erb
source/quick_start_guide/index.html.md.erb
source/refunding_payments/index.html.md.erb
source/reporting/index.html.md.erb

The API reference lives in a bit of a bubble at the moment. Users can find it from the side navigation but it isn't linked to from many places.
Where it makes sense, this PR adds links to the API reference.

PP9297 - Improves linking to the API reference

---

source/api_reference/index.html.md.erb

Because of the way the tech docs template works, the headings on the top-level API reference page do not appear in the left navigation pane. The page is long, so not having the headings available makes the page hard to navigate.
This PR adds a short, bullet point list to the top of the API reference page. Each point links to the relevant heading on that page.

PP10031: Adds anchor links to the top-level reference page

---

source/webhooks/index.html.md.erb

Correct a number of propreties that have been updated since this fixture was written (to make them more consistent with Pay API format).
Address missing ',' to make the JSON valid.
Relates to https://github.com/alphagov/pay-webhooks/pull/419

BAU Correct webhook message body fixture

---

config.rb

When we restructured the MOTO payment documentation ([PP-9135](https://payments-platform.atlassian.net/browse/PP-9136)), we changed the location of the primary authorisation API docs. Some users still accessed those docs through a direct link, so this link is now 404ing.
This PR redirects users that use the old URL (/send_card_details_api) to the new URL (/moto_payments/moto_send_card_details_api).

PP-10200: Redirects the old auth API page to new MOTO section

---

source/making_payments/index.html.md.erb

After we created Pay's API reference, a lot of content in the task-based Pay documentation became redundant/duplicated. [PP-9989](https://payments-platform.atlassian.net/browse/PP-9989) aims to remove that duplicated content.
This PR is [PP-10120](https://payments-platform.atlassian.net/browse/PP-10120) and:
* removes full descriptions of request parameters and response attributes for `POST /v1/payments` endpoint
* replaces full descriptions with links to the reference
* adds better introductory sentences to request/response examples
* fixes some passive voice in old content
I know 'amount' is not a great heading but changing it will break _a lot_ of links elsewhere in the documentation, so I've kept it for now.

PP-10120: Simplifies Take a payment by removing duped content

---

.github/workflows/detect-secrets.yml
.pre-commit-config.yaml
.secrets.baseline

See https://github.com/alphagov/pay-webhooks/pull/510 for details.
This repository didn't have any Github Actions workflows set up - given this is a public repository I think it's worth adding a detect-secrets workflow here. I've enabled this and added the `actions/checkout` to the approved actions list in the repo settings.

PP-10116: Update detect-secrets to 1.4.0, add GHA workflow

---

source/support_contact_and_more_information/index.html.md.erb

The incident prioritisation table in the public docs contradicts the equivalent table in the team docs, and sets up users to expect their issue to be treated more urgently than it will be
Clarifies when users' should expect their issues to be addressed and attempts to give them pause before using out of hours support.

PP-10243 - Changes to Support page

---

source/recurring_payments/index.html.md.erb
source/testing_govuk_pay/index.html.md.erb

To test recurring payments, users can use existing mock card numbers. These existing card numbers can only provide successful OR declined payments. To test every situation for recurring payments, services need a mock card number that can be successful once (to set up the agreement), then fail subsequent attempts.
This PR:
- adds recurring payments mock card under a new heading
- adds a link to the new mock card from the main recurring payments docs page

PP-10595: Adds mock card number for recurring payments

---

source/recurring_payments/index.html.md.erb

Recurring payments supports idempotency to prevent services charging paying users multiple times for the same payment.
Idempotency is documented but we haven’t yet build our implementation of idempotency. Our implementation may change from what is currently documented.
This PR:
- removes some of the existing detail from the idempotency section of the recurring payments docs, in case our implementation changes
- adds a disclaimer to the top of [idempotency section](https://docs.payments.service.gov.uk/recurring_payments/#use-idempotency-to-avoid-double-charging-a-user), explaining that idempotency is not built yet and could change

PP-10626: Add disclaimers to idempotency docs

---

source/moto_payments/moto_send_card_details_api/index.html.md.erb

On the ‘Use an external system to take MOTO payments by sending card details through the API’ page, fix `"authorisation_mode": "moto_api"` so it has "straight quotation marks" rather than “curly quotation marks” (because it’s code and not a beautifully-typeset novel).

BAU — Fix quotation marks on MOTO card details through API page

---

source/testing_govuk_pay/index.html.md.erb

In the list of mock card numbers, replace 5101110000000004 with 5555555555554444. The BIN range that has 5101110000000004 in it has now been allocated to a bank.
Both the old and the new card numbers are non-prepaid, non corporate Mastercard credit cards.
The sandbox card numbers in connector have already been updated to recognise the new card number. Card ID did not need updating as the BIN range that has 5555555555554444 in it was already present in the test file.

ZD-5266603 Replace mock card 5101110000000004 with 5555555555554444

---

ci/pipeline.yml

build-and-deploy fails, build-pr does not fail.
Lets make them identical, and make it easier to diagnose the failed step by enabling -x in bash (to echo the command before running it)
1. Use npm ci instead of install
2. Use npm --omit=dev instead of --only=production (a warning tells you do to this when it runs --only=production)
3. Make build-pr perform the same steps as build-and-deploy for their build step.

BAU: Use npm ci instead of install, and make pr-build the same as build-and-deploy

---

source/recurring_payments/index.html.md.erb
source/webhooks/index.html.md.erb

We are releasing webhooks and recurring payments to all Pay services. The docs for these features currently have warning text about them being in development
- Removes the beta warning text from the webhooks documentation
- Removes the beta warning text from the recurring payments documentation

PP-11086 - Removes beta warning text

---

source/webhooks/index.html.md.erb

We previously advised a 15 second limit on services acknowledging receipt of a webhook message. As per [PP-11060](https://payments-platform.atlassian.net/browse/PP-11060), we should clarify this.
[PP-11060]: https://payments-platform.atlassian.net/browse/PP-11060?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

PP-11085 - Clarifies webhook receipt timing

---

source/recurring_payments/index.html.md.erb
source/testing_govuk_pay/index.html.md.erb

We have test card numbers for Stripe test accounts for one-off payments in tech docs https://docs.payments.service.gov.uk/testing_govuk_pay/#if-you-39-re-using-a-test-stripe-account 
Stripe provides different card numbers to test recurring card payments which cover different scenarios https://stripe.com/docs/payments/save-during-payment?platform=web#web-test-the-integration and can be added to tech docs.
This PR:
- adds a new 'Testing recurring payments on a test Stripe account' heading
- adds a table with mock cards for testing RPs on Stripe
- clarifies some wording for mock RP cards on GOV.UK Pay testing accounts
- explains earlier on the page that Stripe and gov.uk Pay test accounts have different sets of mock cards

PP-11088: Adds RP test cards for Stripe accounts

---

source/api_reference/index.html.md.erb
source/security/index.html.md.erb
source/versioning/index.html.md.erb

Small PR that fixes a few review dates. Reviewer entered `2022` instead of `2023`, causing some issues with the review bot.

Fixes mistyped review dates

---

source/recurring_payments/index.html.md.erb
source/switching_to_live/set_up_a_live_worldpay_account/index.html.md.erb

We've added a new screen for services that process recurring payments with Worldpay. The new screen lets users add their customer initiated transaction (CIT) and merchant initiated transaction (MIT) Worldpay credentials for the initial setup payment and subsequent recurring payments, respectfully.
* Worldpay Go live guidance
* adds step numbers to headings
* splits step 3 into:
* 3a: Connect your [GOV.UK](http://gov.uk/) Pay one-off payments or MOTO payments service to your Worldpay account
* 3b: Connect your [GOV.UK](http://gov.uk/) Pay recurring payments service to your Worldpay account
* add step by steps instructions to step 3b, making sure that:
* Worldpay UI text is accurate
* admin tool UI text is accurate with Alan’s content
* Take recurring payments
* adds a link to the Go live …

PP-11325 - Worldpay recurring payment credentials

---

source/account_structure/index.html.md.erb
source/account_structure/set_up_where_payments_go/index.html.md.erb
source/account_structure/set_up_where_services_link_to/index.html.md.erb
source/api_reference/cancel_payment_reference/index.html.md.erb
source/api_reference/capture_payment_reference/index.html.md.erb
source/api_reference/payment_event_reference/index.html.md.erb
source/api_reference/payment_refunds_reference/index.html.md.erb
source/api_reference/refund_payment_reference/index.html.md.erb
source/api_reference/refund_status_reference/index.html.md.erb
source/api_reference/search_disputes_reference/index.html.md.erb
source/api_reference/search_refunds_reference/index.html.md.erb
source/api_reference/send_card_details_moto_reference/index.html.md.erb
source/block_prepaid_cards/index.html.md.erb
source/corporate_card_surcharges/index.html.md.erb
source/delayed_capture/index.html.md.erb
source/index.html.md.erb
source/optional_features/prefill_user_details/index.html.md.erb
source/optional_features/use_your_own_error_pages/index.html.md.erb
source/optional_features/welsh_language/index.html.md.erb
source/payment_flow/index.html.md.erb
source/prefill_payment_links/index.html.md.erb
source/refunding_payments/index.html.md.erb
source/support_contact_and_more_information/index.html.md.erb
source/switch_payment_service_provider/index.html.md.erb
source/switch_payment_service_provider/switch_psp_to_stripe/index.html.md.erb
source/switch_payment_service_provider/switch_psp_to_worldpay/index.html.md.erb
source/versioning/index.html.md.erb

Documentation reviews are more frequent than is needed for a lot of pages in the GOV.UK Pay documentation. Many pages have been the same for a long time and, when they are reviewed, do not need any changes.
This PR extends the `review_in` time from `6 months` to `12 months` or from `3 months` to `6 months` on pages that have not been updated in a while and will not be worked on in the near future.

PP-11343: Extend review time for established pages

---

source/digital_wallets/index.html.md.erb

As part of https://payments-platform.atlassian.net/browse/PP-11391 , we were adding a table to the digital wallet documentation to clarify how Pay handles cardholder information for wallet payments.
In preparing for digital wallets, Clean Air Zones (CAZ) need to know which cardholder information we’ll store. Because they’re outside of GDS, the easiest way to give them this information is to publish it in the docs before the rest of the changes to that page.
- adds a table for cardholder information to the digital wallet page in the docs

PP-11539: Adds table about cardholder information

---

source/digital_wallets/index.html.md.erb
source/recurring_payments/index.html.md.erb

We’re adding digital wallet support for Stripe services.
* Take a digital wallet payment
* explain that digital wallets are enabled by default for Stripe
* clarify that the ‘Enable Apple Pay’ and ‘Enable Google Pay’ headings are for Worldpay services only
* add ‘Disable Apple Pay’ heading
* add ‘Disable Google Pay’ heading
* add information about testing digital wallet payments
* Take a recurring payment
* mention that users cannot use a digital wallet payments to set up an agreement for recurring payments

PP-11391 - Adds testing information for wallets

---

source/support_contact_and_more_information/scheduled_maintenance/index.html.md.erb

Pay will have three periods of downtime during November for postgres updates. 
We’ve emailed users about this but we’d like to offer more information on a temporary page in our documentation.
This PR:
* creates a new page in the 'Support' section of the tech docs - 'Scheduled GOV.UK Pay maintenance'

PP-11637 - Postgres update information in the documentation

---

source/support_contact_and_more_information/scheduled_maintenance/index.html.md.erb

A couple of small tweaks to the postgres update page:
* explains that recurring payments will not be available during partial outages
* clarifies the types of payments services can take during outages

Small tweaks on postgres maintenance

---

source/digital_wallets/index.html.md.erb

Since enabling digital wallets for Stripe, we've had multiple support requests because users haven't been able to see the wallet buttons. We've also had multiple enquiries about potential additional fees for using Google Pay and/or Apple Pay.
This PR:
* clarifies the situations users can pay with Google Pay and Apple Pay
* clarifies that there are no additional fees for wallet payments

PP-11669 - Clarifies where wallets are available and fees

---

source/corporate_card_surcharges/index.html.md.erb
source/delayed_capture/index.html.md.erb
source/digital_wallets/index.html.md.erb
source/optional_features/use_your_own_error_pages/index.html.md.erb
source/support_contact_and_more_information/scheduled_maintenance/index.html.md.erb
source/switching_to_live/set_up_a_live_stripe_account/index.html.md.erb
source/testing_govuk_pay/index.html.md.erb

We’ve identified a need for a few small documentation changes through reviews and support tickets. These changes are not large enough to need a whole ticket to themselves, so they’re aggregated into this one.
- Corporate card fee page - remove inverted commas from response attribute names
- Use your own payment failure pages - link for payment status goes to the wrong page at the moment
- Use Welsh - link text currently implies that we have specific instructions for Welsh pages when the link should only go to the generic create payment docs page
- Testing integration - clarify the testing actions for recurring card payment cards
- Scheduled downtime - fix time formatting from 4am to 4:00am
- Go live with Stripe - make it clear that services need a real, physical address, and not a PO box …

PP-11787: Minor docs changes based on feedback

---

source/digital_wallets/index.html.md.erb

Digital wallets cannot be used to set up and take recurring payments. We already mention this on the recurring payments docs page, but not on the page for digital wallet payments.
This PR:
* adds a sentence to [Take a digital wallet payment](https://docs.payments.service.gov.uk/digital_wallets/) that explains recurring payments can't be taken with wallets
* adds a H3 to the Take a digital wallet payment page to better organise the cardholder information restrictions from other restrictions

Clarifies recurring payments and adds a new heading for digital wallet payments

---

source/api_reference/index.html.md.erb

[As pointed out in X-gov Slack](https://ukgovernmentdigital.slack.com/archives/C0L3AB342/p1702383666152349), we have a rogue placeholder line saying that recurring payment API endpoints aren't available yet.
This PR removes the placeholder line.

Removes placeholer line about recurring payment endpoint availability

---

source/webhooks/index.html.md.erb

Our documentation doesn't mention some of the restrictions we have on callback URLs for webhooks.
This PR clarifies that (from the JIRA ticket):
- test webhook callback URLs have no domain restrictions
- live webhook callback URLs must have a domain that ends in .gov.uk
- a service can request a domain be allowed for live webhook callback URLs by emailing support
- we will only allow domains that exclusively belong to the service or its parent organisation
- even we decide to allow a domain, it will not be added immediately

PP-11369: Adds information about webhook callback URL restrictions

---

source/delayed_capture/index.html.md.erb
source/making_payments/index.html.md.erb
source/optional_features/prefill_user_details/index.html.md.erb
source/optional_features/welsh_language/index.html.md.erb
source/quick_start_guide/index.html.md.erb
source/reporting/index.html.md.erb

We have some odd example API requests throughout the Pay documentation. Some of them are too verbose, and some pages need examples but don’t have them. 
For example, on the [Take a payment](https://docs.payments.service.gov.uk/making_payments/#creating-a-payment) page, the first request example should be as simple as possible and just contain the required parameters - `amount`, `reference`, `description`, and `return_url`. Instead, it (confusingly) contains lots of optional parameters, like `delayed_capture` and `prefilled_cardholder_details`. 
This is unnecessary when we consider the probable user of this page - a developer that’s new to Pay and wants to know how to create a basic payment.
* Take a payment
* removes optional parameters from the first create payment request example
* …

PP-12141: Improve API request examples

---

source/making_payments/index.html.md.erb
source/moto_payments/moto_api/index.html.md.erb
source/payment_flow/index.html.md.erb
source/recurring_payments/index.html.md.erb
source/refunding_payments/index.html.md.erb
source/webhooks/index.html.md.erb

A lot of the pages in the tech docs have pre-requisites that we don’t really spell out. For example, ‘Take recurring payments’ makes more sense if readers have an understanding of how standard payments work. Similarly, ‘Take a payment’ requires users to have some technical knowledge to understand how APIs work.
This PR:
* tells services that they'll need a technical team to:
* take recurring payments 
* use webhooks
* directs services to payment links if they don't have a tech team
* warns members of the public that the 'Refunding a payment' page is not for them
* adds a request example to a MOTO payment docs page

PP-12251: Adds some signposting to some API-only features

---

source/quick_start_guide/index.html.md.erb

Change stems from docs review.
This PR removes Postman and Insomnia as recommended API clients for testing, because of recent security concerns.
Replaced with Bruno, the client the team has been widely using since Postman.

PP-12078: Removed Postman and Insomnia recommendations

---

source/recurring_payments/index.html.md.erb

Add new section with example emails services can send to their users
Has been checked by @NathanD-GDS

Add new section with example emails services can send to their users

---

source/javascripts/analytics.js
source/javascripts/application.min.js
source/javascripts/application.test.js

Google is sunsetting Universal Analytics (GA3) at the end of June 2024.
The new version of analytics, GA4, recommends the use of Google Tag Manager. This is a functionality provided by Google, whereby arbitrary code may be entered into the Google Analytics console and then injected into a script on the application page.
The Google Tag Manager process bypasses Pay's [secure development requirements](https://manual.payments.service.gov.uk/manual/policies-and-procedures/software-development-lifecycle.html) (prioritisation, code written by trained software developers, code review and security testing) and is therefore not acceptable for use in any applications in the card data environment (CDE) or any applications that affect the CDE, as our PCI compliance would be at risk.
Google tag …

PP-12559 Migrate from google analytics to gtag

---

.github/workflows/static.yml
README.md

Long overdue renaming of the default branch, to avoid outdated language and be consistent with our other repositories. I've already renamed the branch in the settings - as you can see, this PR is now attempting to merge into `main`. 
This PR changes the post-deploy workflow to trigger on merges to the `main` branch.
The tech-docs-gem repo renamed its default branch a while back, so I've updated its README link too.

PP-12761: Rename default branch to main

---

source/testing_govuk_pay/index.html.md.erb

Adds a small warning to the top of the 'Test your integration' page, telling users we will be limiting test accounts and to not request any more.

PP-12763 - Adds a warning about upcoming test account changes

---

source/moto_payments/index.html.md.erb
source/security/index.html.md.erb

GOV.UK Pay is now compatible with PCI DSS v4.0. Our services need to comply by March 2025.
This PR updates references to 3.2.1 to 4.0. It also removes text about our 'upcoming 4.0 updates'.

PP-13009 - Updated PCI 3.2.1 reference to 4.0

---

source/quick_start_guide/index.html.md.erb
source/switching_to_live/index.html.md.erb
source/testing_govuk_pay/index.html.md.erb

When organisations create a service, we now ask them what type of organisation they are. Their answer will determine the type of test account we give them (Stripe or sandbox)
- **Test your integration**
- Reword it so that the ‘default’ is for Stripe services to have a Stripe test account, Worldpay services to have sandbox test account
- Reflect new process for requesting a Stripe test account
- **Quick start**
- Mention that you need to add a new service (this should be there already but isn’t) 
- **Go live**
- Change wording of ‘tell us your PSP’ to something like ‘confirm your PSP’ because organisations have already chosen their PSP during service creation

PP-13093: Changes to reflect the new test account system

---

source/making_payments/index.html.md.erb
source/optional_features/prefill_user_details/index.html.md.erb

WCAG 2.2 specifies that services should not ask users for the same information twice in a single session. We should encourage Pay services to use the `prefilled_cardholder_information` object if they already gather user's information before handing over to Pay.
* suggests prefilling cardholder information in the Take a payment page
* explains that prefilling can help WCAG 2.2 in the Prefill cardholder information page

PP-11927: Redundant entry info for WCAG 2.2

---

source/quick_start_guide/index.html.md.erb
source/testing_govuk_pay/index.html.md.erb

It is no longer possible to swap a sandbox test account for a Stripe test account within the same GOV.UK Pay service. 
* update 'Test your integration' page:
* reflects the new Stripe test account process
* changed heading from 'Request a Stripe test account' to 'Get a Stripe test account' as it's a self-serve process now
* minor change to Quick start guide

PP-13254: Changes to Stripe test account process

---

.github/workflows/detect-secrets.yml
.github/workflows/run-tests.yml
.github/workflows/static.yml

Updates the following actions:
- `actions/checkout`
- `actions/setup-node`
- `ruby/setup-ruby` (3rd party safelist has been updated in the settings)
- `actions/configure-pages`
- `actions/github-script`
- `actions/upload-artifact` and `actions/deploy-pages` (need to be upgraded together for compatibility)
The post-merge workflow action upgrades worked OK for the team manual (see https://github.com/alphagov/pay-team-manual/pull/2203), so I'm reasonably confident they won't break the deployment here either.

PP-12244: Resolve GitHub Actions deprecation warnings

---

source/webhooks/index.html.md.erb

Following the incident where webhook events were sent multiple times in error, we want to clarify to service users what the normal sending behaviour ('sent at least once') should be.
This PR adds some information to [the 'Retry mechanism' section of the GOV.UK Pay webhooks docs](https://docs.payments.service.gov.uk/webhooks/#retry-mechanism).

PP-13369: Information about webhooks retry mechanism

---

source/testing_govuk_pay/index.html.md.erb

Services can connect Worldpay test accounts to Pay, but we want to heavily discourage them.
Adds a small section to the 'Test your integration' page that outlines how to request a Worldpay test account.

PP-13107: Add instructions for requesting a Worldpay test account

---

config/tech-docs.yml
source/accessibility.html.md.erb

In late 2024 and early 2025, we ran an accessibility audit on different parts of GOV.UK Pay, including the tech docs.
This audit identified one potential change.
* updates the accessibility statement with new wording and headings
* updates the suffix in the page title from `Pay` to `Pay technical documentation` to make tabs more identifiable for screen reader users

PP-13550: Update accessibility statement and page titles

---

source/testing_govuk_pay/index.html.md.erb

Per https://github.com/bbyars/mountebank mountebank is no longer maintained and the mbtest.org domain is no longer controlled by the project so remove references to it (we still suggest WireMock).

BAU — Remove references to mountebank

---

source/reporting/index.html.md.erb

Pay has some discrepancies with how it reports timezone across the API, the admin tool, and CSV exports. This has caused issues for services' reporting and reconciliation.
This PR tries to clarify timezones across GOV.UK Pay, while we decide how to make it clearer within the product.
This PR:
* adds a 'Timezones in GOV.UK Pay' section to the reconciling and reporting page which:
* clarifies API timezones
* clarifies admin tool timezones
* links users to the GOV.UK page about changing clocks
* adds a new link to the top of the reporting page to link to timezone guidance
* adds links to timezone guidance where appropriate

PP-13662: Adds guidance about timezones

---

source/switching_to_live/index.html.md.erb
source/switching_to_live/set_up_a_live_stripe_account/index.html.md.erb
source/switching_to_live/set_up_a_live_worldpay_account/index.html.md.erb

This PR makes the GOV.UK Pay documentation reflect the updated go-live process in the admin tool.
It affects:
- Go live
- Connect your live account to Stripe
- Connect your live account to Worldpay

PP-13395: Upates going live docs for simplified Settings

---

source/optional_features/custom_branding/index.html.md.erb
source/optional_features/custom_paragraph/index.html.md.erb
source/optional_features/index.html.md.erb
source/optional_features/welsh_language/index.html.md.erb
source/security/index.html.md.erb

This PR:
* makes the following pages reflect the new simplified Settings screens:
* using Welsh
* Security
* updates the documented custom branding by:
* improving what we ask for services in custom branding requests
* correcting information about reply-to email addresses
* adding templates for services to tell users how to get in touch in payment confirmation emails
* adding a new page for custom content in payment confirmation emails
* changes the name of the 'Customise your payment pages' section to 'Customise your payment pages and emails' to better reflect the content
* adds link to the top-level page to the new sub-page

PP-13395: Restructured custom branding section, minor page changes for simplified Settings

---

source/making_payments/index.html.md.erb
source/payment_flow/index.html.md.erb

We’ve had a few support requests wanting information about whether users can make payments from outside the UK and, if they can, how they differ from payments from within the UK.
There is not a natural place for this to live in the docs as they are, so I’m going to add a ‘Additional considerations when taking payments’ heading to the bottom of the [‘Taking a payment’ page](https://docs.payments.service.gov.uk/making_payments). This will act as a bit of a catch-all for information that does not have a natural home.
This PR:
* adds a section to the bottom to the 'Take a payment' page of the docs
* adds a link to the new section to 'How GOV.UK Pay works'

PP-8405: Adds information about users outside of the UK

---

source/account_structure/set_up_where_payments_go/index.html.md.erb
source/account_structure/set_up_where_services_link_to/index.html.md.erb
source/digital_wallets/index.html.md.erb
source/integrate_with_govuk_pay/index.html.md.erb
source/moto_payments/moto_api/index.html.md.erb
source/optional_features/custom_branding/index.html.md.erb
source/optional_features/custom_paragraph/index.html.md.erb
source/optional_features/index.html.md.erb
source/payment_flow/index.html.md.erb
source/reporting/index.html.md.erb
source/security/index.html.md.erb
source/support_contact_and_more_information/index.html.md.erb

This is a compilation of suggestions gathered over the course of a few months.
In this PR, we:
- fix a typo on the MOTO pages
- add ‘reporting columns’ references to metadata
- adjust weighting of ‘integrate with API’ page to be higher
- improve ‘[Overview’ heading on How Pay works](https://docs.payments.service.gov.uk/payment_flow/#overview)
- add a little use case to custom branding page / rename to ‘Add your organisation branding’
- add a note to the Test your integration page that explains some features (e.g. 3DS) may behave differently when they go live
- change ‘digital wallet’ title to ‘Apple Pay and google Pay’ in a few places
- change ‘Security’ to ‘Security and compliance’
- change ‘Support’ to ‘Get support’

PP-14369: Minor changes for August 2025

---

source/reporting/index.html.md.erb

- We now support up to 15 key-value pairs in the metadata

BAU - update number of metadata key-values allowed
